import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

type Msg={role:"user"|"assistant";content:string;brand?:string|null};
type Mode="fast"|"analyst"|"deep";
type Runtime={enabled?:boolean;model?:string|null;api_key?:string|null};

const norm=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const cleanMsgs=(v:unknown):Msg[]=>Array.isArray(v)?v.filter((x:any)=>x&&(x.role==="user"||x.role==="assistant")&&typeof x.content==="string").map((x:any)=>({role:x.role,content:x.content.trim().slice(0,3000),brand:typeof x.brand==="string"?x.brand:null})).filter((x:Msg)=>x.content).slice(-16):[];
const outputText=(r:any)=>typeof r?.output_text==="string"?r.output_text.trim():(r?.output??[]).flatMap((x:any)=>x?.content??[]).filter((x:any)=>x?.type==="output_text"&&typeof x.text==="string").map((x:any)=>x.text).join("\n").trim();
const followUp=(q:string)=>/^(?:\s|[¿¡])*(?:y\b|pero\b|entonces\b|ahora\b|adem[aá]s\b|tambi[eé]n\b|el\b|la\b|los\b|las\b|ese\b|esa\b|esos\b|esas\b|qu[eé]\b|cu[aá]nto\b|d[oó]nde\b|cu[aá]l\b|c[oó]mo\b|comp[aá]r|expl[ií]ca|profundiza|detalla|por qu[eé]\b)/i.test(q);
const smallTalk=(q:string)=>/^(hola|holi|buenas|gracias|ok|perfecto|dale|qu[eé] puedes hacer|ayuda)[.!?\s]*$/i.test(q.trim());

function modeFor(q:string):Mode{const t=norm(q);if(/estrateg|oportunidad|recomiend|recomend|diagnost|profund|por que|causa|plan de accion|competidor|compara.*con|movimiento|subieron|bajaron|cambio|cambios|desde|histor|evoluc|ultimos (30|60|90)|tendencia.*promoc|anomal/.test(t)||q.length>180)return"deep";if(/precio|barat|caro|compar|brecha|stock|disponib|oferta|promoc|tendencia|retailer|cadena|surtido|producto|sku|base|datos|scrap|cobertura/.test(t)||q.length>90)return"analyst";return"fast";}
function segment(q:string){const t=norm(q);const format=/\blata\b/.test(t)?"lata":/\bbotella\b/.test(t)?"botella":/\bbolsa\b/.test(t)?"bolsa":/\bcaja\b/.test(t)?"caja":/\bfrasco\b/.test(t)?"frasco":/\bpote\b/.test(t)?"pote":/\bsachet\b/.test(t)?"sachet":null;const m=t.match(/\b(\d{2,4})\s*(?:ml|cc)\b/),l=t.match(/\b(\d+(?:[.,]\d+)?)\s*(?:l|lt|litro|litros)\b/);let volumeMl=m?Number(m[1]):l?Math.round(Number(l[1].replace(",","."))*1000):null;if(!Number.isFinite(volumeMl)||Number(volumeMl)<=0||Number(volumeMl)>20000)volumeMl=null;const packageMode=/\b(pack|multipack|x\s*[2-9]\d*)\b/.test(t)?"multipack":/\b(unidad|individual|x\s*1)\b/.test(t)?"single":"all";return{active:Boolean(format||volumeMl||packageMode!=="all"),format,volumeMl,packageMode};}
function variant(q:string){const t=norm(q);if(/\bzero\b|sin azucar/.test(t))return{active:true,label:"Zero",include:["zero"],exclude:["oreo","marshmello","fanta","sprite"]};if(/\blight\b/.test(t))return{active:true,label:"Light",include:["light"],exclude:[]};if(/\b(original|clasica|tradicional)\b/.test(t))return{active:true,label:"Original",include:[],exclude:["zero","light","sin azucar"]};return{active:false,label:null,include:[] as string[],exclude:[] as string[]};}
const effort=(mode:Mode)=>mode==="deep"?"high":mode==="analyst"?"medium":"low";
const supportsReasoning=(model:string)=>/^gpt-5/i.test(model)||/^o\d/i.test(model);
const cleanDate=(v:any)=>typeof v==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(v)?v:null;

function usableModelId(id:string){const x=id.toLowerCase();if(/audio|realtime|image|transcrib|tts|search|codex|chat|instruct|embedding|moderation/.test(x))return false;return /^gpt-5/.test(x)||/^gpt-4\.1/.test(x)||/^o3/.test(x)||/^o4-mini/.test(x)||/^o1/.test(x);}
function modelScore(id:string,mode:Mode){const x=id.toLowerCase();let s=0;const ver=x.match(/^gpt-5(?:\.(\d+))?/);if(ver){s=1000+(ver[1]?Number(ver[1])*20:0);if(/pro/.test(x))s+=mode==="deep"?250:-80;if(/mini/.test(x))s+=mode==="fast"?120:-150;if(/nano/.test(x))s+=mode==="fast"?40:-300;}else if(/^o3-pro/.test(x))s=mode==="deep"?900:650;else if(/^o3/.test(x))s=820;else if(/^o4-mini/.test(x))s=760;else if(/^gpt-4\.1/.test(x))s=650;else if(/^o1/.test(x))s=600;if(/-\d{4}-\d{2}-\d{2}$/.test(x))s-=2;return s;}
async function availableModels(apiKey:string){try{const r=await fetch("https://api.openai.com/v1/models",{headers:{authorization:`Bearer ${apiKey}`}});if(!r.ok)return[] as string[];const raw=await r.json().catch(()=>({}));return Array.isArray(raw?.data)?raw.data.map((m:any)=>String(m?.id||"")).filter(Boolean):[];}catch{return[] as string[];}}
function chooseModels(mode:Mode,available:string[],configured?:string|null){const usable=available.filter(usableModelId),ranked=[...usable].sort((a,b)=>modelScore(b,mode)-modelScore(a,mode));const exactConfigured=configured&&configured!=="auto"&&usable.includes(configured)?configured:null;const aliases=ranked.filter(x=>!/-\d{4}-\d{2}-\d{2}$/.test(x));const dated=ranked.filter(x=>/-\d{4}-\d{2}-\d{2}$/.test(x));const fallback=usable.includes("gpt-4.1")?"gpt-4.1":null;return [exactConfigured,...aliases,...dated,fallback].filter((x,i,a):x is string=>Boolean(x)&&a.indexOf(x)===i).slice(0,3);}

async function resolveBrand(client:any,org:string,q:string,filters:any,previous:string|null){const {data}=await client.rpc("enterprise_brand_resolver_candidates",{p_organization_id:org,p_query:q,p_retailer_type:filters.retailerType||"all",p_supermarket:filters.supermarket||null,p_category:filters.category||null,p_limit:20});const candidates=Array.isArray(data?.candidates)?data.candidates:[];if(filters.brand)return{brand:filters.brand,candidates,method:"filter"};const strong=candidates[0];const formatOnly=/^(?:el|la|los|las|ese|esa|esos|esas|y|ahora|pero|tambien|también|de|en|del|con|sin|pack|unidad|individual|multipack|lata|latas|botella|botellas|caja|cajas|bolsa|bolsas|frasco|frascos|pote|potes|sachet|sachets|ml|cc|lt|litro|litros|\d+|x\d+|\s)+$/i.test(q.trim());if(previous&&followUp(q)&&(formatOnly||!strong||Number(strong.score)<.93))return{brand:previous,candidates,method:"conversation_context"};if(strong&&Number(strong.score)>=.97&&["exact","phrase","normalized_exact"].includes(strong.matchType))return{brand:strong.brand,candidates,method:"database_exact"};if(previous&&followUp(q))return{brand:previous,candidates,method:"conversation_context"};if(strong&&Number(strong.score)>=.72)return{brand:strong.brand,candidates,method:"database_fuzzy"};return{brand:null,candidates,method:"unresolved"};}
async function currentContext(client:any,org:string,brand:string,q:string,filters:any){const s=segment(q),v=variant(q),days=Math.max(7,Math.min(90,Number(filters.period)||30));if(v.active)return await client.rpc("enterprise_brand_variant_context_v1",{p_organization_id:org,p_brand:brand,p_name_terms:v.include,p_exclude_terms:v.exclude,p_variant_label:v.label,p_exclude_composites:true,p_format:s.format,p_package_mode:s.packageMode,p_volume_ml:s.volumeMl,p_retailer_type:filters.retailerType||"all",p_supermarket:filters.supermarket||null,p_category:filters.category||null,p_stock:filters.stock||"all",p_days:days});if(s.active)return await client.rpc("enterprise_brand_segment_context_v1",{p_organization_id:org,p_brand:brand,p_format:s.format,p_package_mode:s.packageMode,p_volume_ml:s.volumeMl,p_retailer_type:filters.retailerType||"all",p_supermarket:filters.supermarket||null,p_category:filters.category||null,p_stock:filters.stock||"all"});return await client.rpc("enterprise_brand_intelligence_context_v5",{p_organization_id:org,p_brand:brand,p_retailer_type:filters.retailerType||"all",p_supermarket:filters.supermarket||null,p_category:filters.category||null,p_stock:filters.stock||"all",p_days:days});}
async function pricePosition(client:any,org:string,brand:string,q:string,filters:any){const {data:pre,error}=await client.rpc("enterprise_price_map_preflight",{p_organization_id:org,p_brand:brand,p_question:q,p_retailer_type:filters.retailerType||"all",p_supermarket:filters.supermarket||null,p_category:filters.category||null,p_stock:filters.stock||"all"});if(error||!Array.isArray(pre?.clusters)||!pre.clusters.length)return{found:false};const c=pre.clusters[0];const {data,error:ce}=await client.rpc("enterprise_ai_price_map_context_v4",{p_organization_id:org,p_brand:brand,p_category:c.category,p_format:c.format??null,p_measure_type:c.measureType,p_size_bucket:c.sizeBucket??null,p_retailer_type:filters.retailerType||"all",p_supermarket:filters.supermarket||null,p_stock:filters.stock||"all"});if(ce||!data?.found)return{found:false};return{found:true,cluster:c,category:data.category,format:data.format,measureType:data.measureType,sizeBucket:data.sizeBucket,priceBasis:data.priceBasis,quality:data.quality,targetRetailers:data.targetRetailers,points:(data.points??[]).slice(0,16)};}
async function trend(client:any,org:string,brand:string,filters:any,days:number){const {data,error}=await client.rpc("enterprise_contextual_pricing_trend",{p_organization_id:org,p_days:Math.max(7,Math.min(365,days||30)),p_retailer_type:filters.retailerType||"all",p_supermarket:filters.supermarket||null,p_category:filters.category||null,p_brand:brand,p_stock:filters.stock||"all"});return error?{error:error.message}:data;}
async function matches(client:any,org:string,brand:string,filters:any,limit:number){const {data,error}=await client.rpc("enterprise_price_matches",{p_organization_id:org,p_page:1,p_page_size:Math.max(5,Math.min(30,limit||15)),p_query:null,p_category:filters.category||null,p_brand:brand,p_min_savings:0,p_coverage:"all",p_quality:"all",p_sort:"gap_desc"});return error?{error:error.message}:data;}
async function compareBrand(client:any,org:string,brand:string,filters:any){const {data,error}=await client.rpc("enterprise_brand_intelligence_context_v5",{p_organization_id:org,p_brand:brand,p_retailer_type:filters.retailerType||"all",p_supermarket:filters.supermarket||null,p_category:filters.category||null,p_stock:filters.stock||"all",p_days:Math.max(7,Math.min(90,Number(filters.period)||30))});return error?{error:error.message}:data;}
async function dataInventory(client:any,org:string,days:number){const {data,error}=await client.rpc("enterprise_ai_data_inventory_v1",{p_organization_id:org,p_days:Math.max(7,Math.min(365,days||30))});return error?{error:error.message}:data;}
async function databaseSearch(client:any,org:string,args:any,filters:any,defaultBrand:string|null,q:string){const requested=String(args?.query||"").trim();const s=segment(q),v=variant(q);const fallback=[defaultBrand,v.label,s.format,s.volumeMl?`${s.volumeMl} ml`:null].filter(Boolean).join(" ");const search=requested||fallback||q;const {data,error}=await client.rpc("enterprise_ai_catalog_history_search_v1",{p_organization_id:org,p_query:search.slice(0,180),p_brand:typeof args?.brand==="string"&&args.brand.trim()?args.brand.trim():defaultBrand,p_retailer_type:typeof args?.retailerType==="string"&&args.retailerType?args.retailerType:(filters.retailerType||"all"),p_supermarket:typeof args?.supermarket==="string"&&args.supermarket?args.supermarket:(filters.supermarket||null),p_category:typeof args?.category==="string"&&args.category?args.category:(filters.category||null),p_days:Math.max(7,Math.min(365,Number(args?.days)||Number(filters.period)||30)),p_limit:Math.max(5,Math.min(40,Number(args?.limit)||24))});return error?{error:error.message}:data;}
async function priceMovements(client:any,org:string,args:any,filters:any,defaultBrand:string|null){const {data,error}=await client.rpc("enterprise_ai_price_movements_v1",{p_organization_id:org,p_brand:typeof args?.brand==="string"&&args.brand.trim()?args.brand.trim():defaultBrand,p_retailer_type:typeof args?.retailerType==="string"&&args.retailerType?args.retailerType:(filters.retailerType||"all"),p_supermarket:typeof args?.supermarket==="string"&&args.supermarket?args.supermarket:(filters.supermarket||null),p_category:typeof args?.category==="string"&&args.category?args.category:(filters.category||null),p_start_date:cleanDate(args?.startDate),p_end_date:cleanDate(args?.endDate),p_direction:["up","down","changed","both"].includes(args?.direction)?args.direction:"both",p_limit:Math.max(5,Math.min(40,Number(args?.limit)||20))});return error?{error:error.message}:data;}

const tools=[
{type:"function",name:"get_data_inventory",description:"Consulta qué datos existen realmente en la base: primera y última fecha disponible, cobertura por día, retailers, marcas y categorías. Úsala para preguntas sobre cobertura, desde cuándo hay datos, qué hay en la base o cuando necesites conocer el horizonte histórico.",parameters:{type:"object",properties:{days:{type:"integer",minimum:7,maximum:365}},required:[],additionalProperties:false}},
{type:"function",name:"search_database",description:"Busca directamente productos reales en la base por nombre o descripción y devuelve precios vigentes, retailers, formatos/tamaños y su histórico diario. Úsala cuando el usuario mencione un producto, variante o presentación concreta, cuando el contexto de marca no alcance, o antes de decir que no hay datos.",parameters:{type:"object",properties:{query:{type:"string",description:"Solo términos del producto a buscar, por ejemplo 'Coca Cola Zero lata 350 ml'; no copies toda la pregunta."},brand:{type:"string"},retailerType:{type:"string"},supermarket:{type:"string"},category:{type:"string"},days:{type:"integer",minimum:7,maximum:365},limit:{type:"integer",minimum:5,maximum:40}},required:["query"],additionalProperties:false}},
{type:"function",name:"get_price_movements",description:"Obtiene cambios reales de precio del mismo SKU entre el primer y último día observado dentro de un período. Úsala para preguntas sobre qué subió, bajó o cambió desde una fecha.",parameters:{type:"object",properties:{brand:{type:"string"},retailerType:{type:"string"},supermarket:{type:"string"},category:{type:"string"},startDate:{type:"string",description:"YYYY-MM-DD"},endDate:{type:"string",description:"YYYY-MM-DD"},direction:{type:"string",enum:["up","down","changed","both"]},limit:{type:"integer",minimum:5,maximum:40}},required:[],additionalProperties:false}},
{type:"function",name:"get_price_position",description:"Obtiene posicionamiento de precio comparable de la marca por cluster homogéneo. Requiere que exista una marca resuelta.",strict:true,parameters:{type:"object",properties:{question:{type:"string"}},required:["question"],additionalProperties:false}},
{type:"function",name:"get_trend",description:"Obtiene evolución histórica agregada de precios de una marca. Requiere que exista una marca resuelta.",strict:true,parameters:{type:"object",properties:{days:{type:"integer",minimum:7,maximum:365}},required:["days"],additionalProperties:false}},
{type:"function",name:"get_price_matches",description:"Obtiene productos homologados y brechas de precio entre retailers para una marca. Requiere marca resuelta.",strict:true,parameters:{type:"object",properties:{limit:{type:"integer",minimum:5,maximum:30}},required:["limit"],additionalProperties:false}},
{type:"function",name:"compare_brand",description:"Obtiene el mismo contexto de otra marca para una comparación directa.",strict:true,parameters:{type:"object",properties:{brand:{type:"string"}},required:["brand"],additionalProperties:false}},
{type:"function",name:"get_market_pulse",description:"Obtiene el pulso ponderado actual por cadena.",strict:true,parameters:{type:"object",properties:{},required:[],additionalProperties:false}}
];

async function callResponses(apiKey:string,body:any){const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{authorization:`Bearer ${apiKey}`,"content-type":"application/json"},body:JSON.stringify(body)});const raw=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(raw?.error?.message||`OpenAI ${r.status}`),{status:r.status});return raw;}

async function runAgent(apiKey:string,model:string,mode:Mode,messages:Msg[],base:any,forceTool:boolean,execute:(name:string,args:any)=>Promise<any>){
  const instructions=[
    "Eres MGP Intelligence, un analista senior de pricing, surtido y retail conectado a la base real scrapeada por MGP.",
    "Responde en español natural, preciso y ejecutivo. Cada cifra sobre precios, productos, disponibilidad, fechas o movimientos debe provenir de CURRENT_BASE o de una herramienta de base de datos.",
    "No te limites a una marca. Puedes responder preguntas abiertas sobre productos, retailers, cobertura de datos y movimientos del mercado usando get_data_inventory, search_database y get_price_movements.",
    "Antes de afirmar que no existen datos de un producto o variante, usa search_database. Si la búsqueda es ambigua, explica qué coincidencias reales encontraste y pide una aclaración solo si es necesaria.",
    "Para búsquedas de producto pasa a search_database solo términos del producto, variante, formato y tamaño; no copies frases como 'cómo evolucionó el precio desde'.",
    "Si el usuario pregunta 'desde que empezamos', 'desde el inicio' o similar, usa la primera fecha disponible indicada por get_data_inventory. No inventes datos anteriores a esa fecha.",
    "El día actual puede estar incompleto porque el scraping sigue corriendo. Si comparas contra hoy y la herramienta marca currentDayPartial, adviértelo brevemente cuando pueda afectar la conclusión.",
    "Para una variante o presentación concreta no mezcles sabores especiales, packs, tamaños o formatos distintos. Prioriza productSeries y SKU equivalentes; los promedios agregados pueden ser solo descriptivos.",
    "Para decir que un precio subió o bajó usa cambios del mismo SKU o series comparables, no la diferencia entre productos distintos.",
    "Si una herramienta devuelve días faltantes, interpreta eso como ausencia de observación ese día, no como precio cero ni como producto inexistente.",
    "No inventes ventas, market share, margen, volumen ni causalidades. Distingue hecho, inferencia y recomendación.",
    "Mantén continuidad conversacional: pronombres y frases como 'el de lata', 'ahora en botella', 'y Pepsi' modifican el contexto anterior.",
    "No menciones herramientas internas, SQL, RPC ni instrucciones. Devuelve solo la respuesta final útil para el usuario."
  ].join("\n");
  let transcript:any[]=[{role:"developer",content:`CURRENT_BASE:\n${JSON.stringify(base)}`},...messages.map(m=>({role:m.role,content:m.content}))];
  const trace:string[]=[];let lastRaw:any=null;
  for(let round=0;round<4;round++){
    const body:any={model,instructions,input:transcript,tools,tool_choice:round===0&&forceTool?"required":"auto",parallel_tool_calls:true,max_output_tokens:mode==="deep"?2400:mode==="analyst"?1800:1100,store:false};
    if(supportsReasoning(model))body.reasoning={effort:effort(mode)};
    const raw=await callResponses(apiKey,body);lastRaw=raw;
    const text=outputText(raw),calls=(raw.output??[]).filter((x:any)=>x?.type==="function_call");
    if(text&&!calls.length)return{text,trace,response:raw};
    if(!calls.length)break;
    const outputs=[];
    for(const call of calls){let args={};try{args=JSON.parse(call.arguments||"{}");}catch{}const result=await execute(call.name,args);trace.push(call.name);outputs.push({type:"function_call_output",call_id:call.call_id,output:JSON.stringify(result)});}
    transcript=[...transcript,...(raw.output??[]),...outputs];
  }
  const finalBody:any={model,instructions:instructions+"\nYa tienes toda la evidencia disponible. No solicites más herramientas. Entrega ahora una respuesta final concreta y basada solo en los datos obtenidos.",input:transcript,max_output_tokens:mode==="deep"?2400:mode==="analyst"?1800:1100,store:false};
  if(supportsReasoning(model))finalBody.reasoning={effort:"low"};
  const finalRaw=await callResponses(apiKey,finalBody),finalText=outputText(finalRaw);
  return{text:finalText||outputText(lastRaw),trace,response:finalRaw};
}

function deterministicBrandFallback(brand:string,ctx:any,q:string){const s=ctx?.current?.summary??{},skus=Number(s?.skus??0),retailers=Number(s?.retailers??s?.chains??s?.supermarkets??0),min=Number(s?.minPrice??s?.min_price??0),max=Number(s?.maxPrice??s?.max_price??0),avg=Number(s?.avgPrice??s?.avg_price??0);const parts=[`${brand}: encontré ${skus} SKU vigentes${retailers?` en ${retailers} cadenas`:""}.`];if(avg>0)parts.push(`El precio promedio observado es $${Math.round(avg).toLocaleString("es-CL")}${min>0&&max>0?`, con un rango aproximado entre $${Math.round(min).toLocaleString("es-CL")} y $${Math.round(max).toLocaleString("es-CL")}`:""}.`);const t=norm(q);if(/precio|caro|barato|brecha|compar/.test(t))parts.push("Para comparar precio correctamente hay que homologar formato, tamaño y pack.");else parts.push("Puedo profundizar por cadena, presentación, disponibilidad, promociones o histórico.");return parts.join(" ");}
function deterministicGeneralFallback(inv:any){if(inv?.found)return`La base tiene histórico disponible desde ${inv.firstDate} hasta ${inv.lastDate}, con ${Number(inv.products||0).toLocaleString("es-CL")} productos y ${inv.retailers||0} retailers observados. Puedo buscar un producto, marca, categoría o movimiento de precio concreto dentro de ese período.`;return"No pude obtener el inventario de datos en este momento.";}

Deno.serve(async(req:Request)=>{
  if(req.method!=="POST")return new Response("Method not allowed",{status:405});
  const auth=req.headers.get("authorization")??"",url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  try{
    const body=await req.json().catch(()=>({})),org=typeof body?.organizationId==="string"?body.organizationId:"",messages=cleanMsgs(body?.messages),q=[...messages].reverse().find(m=>m.role==="user")?.content??"";
    if(!org||!q)return Response.json({error:"Falta la organización o la pregunta."},{status:400});
    const user=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:u,error:ue}=await user.auth.getUser();if(ue||!u.user)return Response.json({error:"No autorizado"},{status:401});
    if(smallTalk(q))return Response.json({answer:"Hola. Puedes preguntarme por cualquier producto, marca, cadena, precio, promoción, disponibilidad o evolución histórica que tengamos monitoreada.",brand:null,ai:false,analysisMode:"fast"});
    const svc=createClient(url,service),{data:cfg}=await svc.rpc("get_ai_runtime_config_service"),config=(cfg??{}) as Runtime,filters=body?.filters??{};
    const previousBrand=[...messages].slice(0,-1).reverse().find(m=>m.role==="assistant"&&m.brand)?.brand??null;
    const resolution=await resolveBrand(user,org,q,filters,previousBrand);
    let ctx:any=null,contextError:string|null=null;
    if(resolution.brand){const r=await currentContext(user,org,resolution.brand,q,filters);ctx=r.data;contextError=r.error?.message??null;}
    const t=norm(q),needsInventory=!resolution.brand||/base|datos|scrap|cobertura|desde|inicio|histor|primer|cuando|que hay|tenemos/.test(t);
    let inventory:any=null;
    if(needsInventory){inventory=await dataInventory(user,org,Math.max(30,Number(filters.period)||30));if(inventory?.error)inventory={error:inventory.error};}
    const mode=modeFor(q);
    const base={question:q,brand:resolution.brand??null,brandResolution:{method:resolution.method,candidates:(resolution.candidates??[]).slice(0,5).map((c:any)=>({brand:c.brand,score:c.score,matchType:c.matchType}))},brandContext:ctx?.found?{current:ctx.current,trend:ctx.trend,quality:ctx.quality,scope:ctx.scope,segment:ctx.segment??{...segment(q),variant:variant(q).label}}:null,contextError,dataCoverage:inventory,filters:{retailerType:filters.retailerType||"all",supermarket:filters.supermarket||null,category:filters.category||null,stock:filters.stock||"all",period:Number(filters.period)||30}};
    if(!config.enabled||!config.api_key){const answer=ctx?.found&&resolution.brand?deterministicBrandFallback(resolution.brand,ctx,q):deterministicGeneralFallback(inventory);return Response.json({answer,brand:resolution.brand??null,data:ctx,inventory,ai:false,analysisMode:mode});}

    const execute=async(name:string,args:any)=>{
      if(name==="get_data_inventory")return await dataInventory(user,org,Number(args?.days)||30);
      if(name==="search_database")return await databaseSearch(user,org,args,filters,resolution.brand??null,q);
      if(name==="get_price_movements")return await priceMovements(user,org,args,filters,resolution.brand??null);
      if(name==="get_price_position")return resolution.brand?await pricePosition(user,org,resolution.brand,String(args.question||q),filters):{found:false,error:"brand_required_use_search_database"};
      if(name==="get_trend")return resolution.brand?await trend(user,org,resolution.brand,filters,Number(args.days)||Number(filters.period)||30):{found:false,error:"brand_required_use_search_database"};
      if(name==="get_price_matches")return resolution.brand?await matches(user,org,resolution.brand,filters,Number(args.limit)||15):{found:false,error:"brand_required_use_search_database"};
      if(name==="compare_brand")return await compareBrand(user,org,String(args.brand||""),filters);
      if(name==="get_market_pulse"){const {data,error}=await user.rpc("enterprise_weighted_price_pulse",{p_organization_id:org});return error?{error:error.message}:data;}
      return{error:"unknown_tool"};
    };

    const available=await availableModels(config.api_key),candidates=chooseModels(mode,available,config.model);console.log("MGP model-selection",JSON.stringify({availableCount:available.length,candidates,brand:resolution.brand,contextFound:Boolean(ctx?.found)}));
    const forceTool=mode!=="fast"||!ctx?.found||!resolution.brand;
    for(const model of candidates){try{const result=await runAgent(config.api_key,model,mode,messages,base,forceTool,execute);if(result.text)return Response.json({answer:result.text,brand:resolution.brand??null,model,ai:true,assistant:"MGP Intelligence",responseStyle:"database_agentic",analysisMode:mode,reasoningEffort:supportsReasoning(model)?effort(mode):"none",toolsUsed:result.trace,data:ctx,inventory,resolution,modelSelection:{availableCount:available.length,auto:true,candidates:candidates.length}});}catch(e:any){const status=Number(e?.status),msg=e?.message||String(e);console.warn("MGP model-failed",JSON.stringify({model,status,message:msg.slice(0,300)}));if(![400,403,404,408,409,429,500,502,503,504].includes(status))break;}}
    const answer=ctx?.found&&resolution.brand?deterministicBrandFallback(resolution.brand,ctx,q):deterministicGeneralFallback(inventory);
    return Response.json({answer,brand:resolution.brand??null,data:ctx,inventory,ai:false,warning:"advanced_model_unavailable",analysisMode:mode,responseStyle:"deterministic_fallback",modelSelection:{availableCount:available.length,auto:true,candidates:candidates.length}});
  }catch(e){console.error(e);return Response.json({error:"No pude completar el análisis avanzado."},{status:500});}
});
