import { NextRequest, NextResponse } from "next/server";
import { enterpriseAccess } from "@/lib/enterprise-auth";
import { clickHouseConfigured, clickHouseQuery } from "@/lib/clickhouse";

export const dynamic = "force-dynamic";

type Row={category:string;brand:string;products:number|string;retailers:number|string;median:number|string;promo:number|string;availability:number|string};
const price="if(toFloat64(ifNull(s.offer_price,0))>0,toFloat64(s.offer_price),toFloat64(ifNull(s.regular_price,0)))";
const sql=`SELECT category,brand,uniqExact(id) products,uniqExact(retailer) retailers,round(quantileTDigest(.5)(price),0) median,round(countIf(regular>price)/greatest(count(),1)*100,1) promo,round(countIf(in_stock)/greatest(count(),1)*100,1) availability FROM (SELECT multiIf(b IN ('tissot','seiko','citizen'),'Relojes',b IN ('samsonite','american tourister','saxoline'),'Equipaje',b='leatherman','Navajas y multiherramientas',b IN ('arcos','global','zwilling','tramontina','wusthof'),'Cuchillos',b='victorinox' AND positionCaseInsensitiveUTF8(txt,'reloj')>0,'Relojes',b='victorinox' AND (positionCaseInsensitiveUTF8(txt,'maleta')>0 OR positionCaseInsensitiveUTF8(txt,'equipaje')>0),'Equipaje',b='victorinox' AND (positionCaseInsensitiveUTF8(txt,'navaj')>0 OR positionCaseInsensitiveUTF8(txt,'multiherr')>0),'Navajas y multiherramientas',b='victorinox','Cuchillos','') category,b brand,id,retailer,price,regular,in_stock FROM (SELECT lowerUTF8(ifNull(p.brand,'')) b,toString(p.id) id,p.supermarket retailer,concat(ifNull(p.name,''),' ',ifNull(p.category,''),' ',ifNull(p.smart_category,'')) txt,${price} price,toFloat64(ifNull(s.regular_price,0)) regular,s.in_stock in_stock FROM products p FINAL INNER JOIN product_latest_price_state s FINAL ON s.product_id=p.id WHERE b IN ('victorinox','tissot','seiko','citizen','samsonite','american tourister','saxoline','leatherman','arcos','global','zwilling','tramontina','wusthof') AND price>0)) WHERE category!='' GROUP BY category,brand ORDER BY category,median DESC`;
function n(v:number|string){return Number(v)||0}
export async function GET(req:NextRequest){const a=await enterpriseAccess(req,"overview");if(a.response)return a.response;if(!clickHouseConfigured())return NextResponse.json({error:"ClickHouse no configurado"},{status:503});try{const rows=await clickHouseQuery<Row>(sql,{},5000);const categories=["Cuchillos","Navajas y multiherramientas","Relojes","Equipaje"].map(category=>{const r=rows.filter(x=>x.category===category),own=r.find(x=>x.brand==="victorinox"),comp=r.filter(x=>x.brand!=="victorinox");const meds=comp.map(x=>n(x.median)).filter(Boolean).sort((x,y)=>x-y);const benchmark=meds.length?meds[Math.floor(meds.length/2)]:0,ownMedian=n(own?.median||0),index=benchmark&&ownMedian?Math.round(ownMedian/benchmark*1000)/10:null;return{category,own:own?{products:n(own.products),retailers:n(own.retailers),medianPrice:ownMedian,promoPct:n(own.promo),availabilityPct:n(own.availability)}:null,benchmarkMedian:benchmark,priceIndex:index,premiumPct:index===null?null:Math.round((index-100)*10)/10,competitors:comp.map(x=>({brand:x.brand,products:n(x.products),retailers:n(x.retailers),medianPrice:n(x.median),promoPct:n(x.promo),availabilityPct:n(x.availability),premiumPct:ownMedian&&n(x.median)?Math.round((ownMedian/n(x.median)-1)*1000)/10:null}))}});return NextResponse.json({source:"clickhouse",brand:"Victorinox",categories},{headers:{"cache-control":"private, max-age=60, stale-while-revalidate=300"}})}catch(e){console.error("brands competition",e);return NextResponse.json({error:"No fue posible calcular competencia"},{status:503})}}
