export const BODEGAS_DON_LUIS_PAYLOAD = {
  currency: "PEN",
  brand: {
    id: "demo-bodegas-don-luis",
    slug: "bodegas-don-luis",
    name: "Bodegas Don Luis",
    countryCode: "PE",
    officialUrl: "https://www.bodegasdonluis.pe/",
  },
  summary: {
    products: 7,
    sources: 5,
    listings: 18,
    sellers: 5,
    inStockPct: 100,
    promoPct: 61,
    lastObservedAt: "2026-08-28T19:00:00.000Z",
  },
  sources: [
    { id: "bdl-tottus", retailer_name: "Tottus Perú", domain: "tottus.com.pe", source_type: "supermercado", priority: 1, last_crawled_at: "2026-08-28T19:00:00.000Z", last_status: "public_demo", last_error: null, listings: 7, in_stock: 7, min_price: 13.9, max_price: 86.9 },
    { id: "bdl-metro", retailer_name: "Metro Perú", domain: "metro.pe", source_type: "supermercado", priority: 1, last_crawled_at: "2026-08-28T19:00:00.000Z", last_status: "public_demo", last_error: null, listings: 4, in_stock: 4, min_price: 15.9, max_price: 154.9 },
    { id: "bdl-wong", retailer_name: "Wong", domain: "wong.pe", source_type: "supermercado", priority: 1, last_crawled_at: "2026-08-28T19:00:00.000Z", last_status: "public_demo", last_error: null, listings: 3, in_stock: 3, min_price: 37.9, max_price: 66.9 },
    { id: "bdl-vivanda", retailer_name: "Vivanda", domain: "vivanda.com.pe", source_type: "supermercado", priority: 1, last_crawled_at: "2026-08-28T19:00:00.000Z", last_status: "public_demo", last_error: null, listings: 3, in_stock: 3, min_price: 34.3, max_price: 74.9 },
    { id: "bdl-makro", retailer_name: "Plaza Vea / Makro", domain: "makro.plazavea.com.pe", source_type: "supermercado_mayorista", priority: 2, last_crawled_at: "2026-08-28T19:00:00.000Z", last_status: "public_demo", last_error: null, listings: 3, in_stock: 3, min_price: 40.9, max_price: 76.9 },
  ],
  products: [
    { id: "bdl-p1", sku: "CG-Q-700", ean: null, name: "Pisco Cuatro Gallos Puro Quebranta 700 ml", category: "Pisco", subcategory: "Puro Quebranta", url: "https://www.metro.pe/pisco-puro-quebranta-cuatro-gallos-700ml/p", imageUrl: null, attributes: { brand: "Cuatro Gallos", ml: 700 }, lastSeenAt: "2026-08-28T19:00:00.000Z" },
    { id: "bdl-p2", sku: "CG-I-700", ean: null, name: "Pisco Cuatro Gallos Puro Italia 700 ml", category: "Pisco", subcategory: "Puro Italia", url: "https://www.metro.pe/pisco-puro-italia-cuatro-gallos-700ml/p", imageUrl: null, attributes: { brand: "Cuatro Gallos", ml: 700 }, lastSeenAt: "2026-08-28T19:00:00.000Z" },
    { id: "bdl-p3", sku: "MAN-SOL-700", ean: null, name: "Ron Mandatario Solera 700 ml", category: "Ron", subcategory: "Solera", url: "https://www.vivanda.com.pe/ron-mandatario-solera-botella-700ml/p", imageUrl: null, attributes: { brand: "Mandatario", ml: 700 }, lastSeenAt: "2026-08-28T19:00:00.000Z" },
    { id: "bdl-p4", sku: "ECO-TINTO-750", ean: null, name: "Vino E. Copello Tinto Semiseco 750 ml", category: "Vino", subcategory: "Tinto semiseco", url: "https://www.metro.pe/vino-tinto-semiseco-blend-e-copello-750ml-2/p", imageUrl: null, attributes: { brand: "E. Copello", ml: 750 }, lastSeenAt: "2026-08-28T19:00:00.000Z" },
    { id: "bdl-p5", sku: "ECO-MOS-750", ean: null, name: "Vino E. Copello Blanco Moscato 750 ml", category: "Vino", subcategory: "Blanco Moscato", url: "https://www.tottus.com.pe/tottus-pe/articulo/113368517/vino-ecopello-blanco-moscato-botella-750-ml", imageUrl: null, attributes: { brand: "E. Copello", ml: 750 }, lastSeenAt: "2026-08-28T19:00:00.000Z" },
    { id: "bdl-p6", sku: "CP-CARM-750", ean: null, name: "Vino Casas Patronales Carmenere 750 ml", category: "Vino", subcategory: "Carmenere", url: "https://www.tottus.com.pe/tottus-pe/marca/CASAS%20PATRONALES", imageUrl: null, attributes: { brand: "Casas Patronales", ml: 750 }, lastSeenAt: "2026-08-28T19:00:00.000Z" },
    { id: "bdl-p7", sku: "LAG-CAB-750", ean: null, name: "Vino Lagarde Cabernet Sauvignon 750 ml", category: "Vino", subcategory: "Cabernet Sauvignon", url: "https://www.tottus.com.pe/tottus-pe/marca/LAGARDE", imageUrl: null, attributes: { brand: "Lagarde", ml: 750 }, lastSeenAt: "2026-08-28T19:00:00.000Z" },
  ],
  listings: [
    { id: "bdl-l1", source: "Tottus Perú", domain: "tottus.com.pe", title: "Pisco Cuatro Gallos Quebranta 700 ml", seller: "Cuatro Gallos", category: "Pisco", url: "https://www.tottus.com.pe/tottus-pe/lista/CATG17986/Cuatro-Gallos", imageUrl: null, regularPrice: 44.9, currentPrice: 38.5, currency: "PEN", inStock: true, rating: null, reviewCount: null, observedAt: "2026-08-28T19:00:00.000Z" },
    { id: "bdl-l2", source: "Metro Perú", domain: "metro.pe", title: "Pisco Puro Quebranta Cuatro Gallos 700 ml", seller: "Cuatro Gallos", category: "Pisco", url: "https://www.metro.pe/pisco-puro-quebranta-cuatro-gallos-700ml/p", imageUrl: null, regularPrice: 44.9, currentPrice: 38.9, currency: "PEN", inStock: true, rating: null, reviewCount: null, observedAt: "2026-08-28T19:00:00.000Z" },
    { id: "bdl-l3", source: "Wong", domain: "wong.pe", title: "Pisco Puro Quebranta Cuatro Gallos 700 ml", seller: "Cuatro Gallos", category: "Pisco", url: "https://app.wong.pe/cervezas-vinos-y-licores/licores/pisco/45241", imageUrl: null, regularPrice: 44.9, currentPrice: 38.9, currency: "PEN", inStock: true, rating: null, reviewCount: null, observedAt: "2026-08-28T19:00:00.000Z" },
    { id: "bdl-l4", source: "Vivanda", domain: "vivanda.com.pe", title: "Pisco Cuatro Gallos Quebranta 700 ml", seller: "Cuatro Gallos", category: "Pisco", url: "https://www.vivanda.com.pe/pisco-cuatro-gallos-puro-quebranta-botella-700ml/p", imageUrl: null, regularPrice: 42.9, currentPrice: 39.9, currency: "PEN", inStock: true, rating: null, reviewCount: null, observedAt: "2026-08-28T19:00:00.000Z" },
    { id: "bdl-l5", source: "Plaza Vea / Makro", domain: "makro.plazavea.com.pe", title: "Pisco Cuatro Gallos Quebranta 700 ml", seller: "Cuatro Gallos", category: "Pisco", url: "https://www.makro.plazavea.com.pe/vinos-licores-y-cervezas/licores/pisco/cuatro-gallos", imageUrl: null, regularPrice: 42.9, currentPrice: 40.9, currency: "PEN", inStock: true, rating: null, reviewCount: null, observedAt: "2026-08-28T19:00:00.000Z" },
    { id: "bdl-l6", source: "Metro Perú", domain: "metro.pe", title: "Pisco Cuatro Gallos Italia 700 ml", seller: "Cuatro Gallos", category: "Pisco", url: "https://www.metro.pe/pisco-puro-italia-cuatro-gallos-700ml/p", imageUrl: null, regularPrice: 44.9, currentPrice: 38.5, currency: "PEN", inStock: true, rating: null, reviewCount: null, observedAt: "2026-08-28T19:00:00.000Z" },
    { id: "bdl-l7", source: "Vivanda", domain: "vivanda.com.pe", title: "Pisco Cuatro Gallos Italia 700 ml", seller: "Cuatro Gallos", category: "Pisco", url: "https://www.vivanda.com.pe/pisco-cuatro-gallos-puro-italia-botella-700ml/p", imageUrl: null, regularPrice: 42.9, currentPrice: 34.3, currency: "PEN", inStock: true, rating: null, reviewCount: null, observedAt: "2026-08-28T19:00:00.000Z" },
    { id: "bdl-l8", source: "Plaza Vea / Makro", domain: "makro.plazavea.com.pe", title: "Pisco Cuatro Gallos Italia 700 ml", seller: "Cuatro Gallos", category: "Pisco", url: "https://www.makro.plazavea.com.pe/vinos-licores-y-cervezas/licores/pisco/cuatro-gallos", imageUrl: null, regularPrice: 42.9, currentPrice: 40.9, currency: "PEN", inStock: true, rating: null, reviewCount: null, observedAt: "2026-08-28T19:00:00.000Z" },
    { id: "bdl-l9", source: "Wong", domain: "wong.pe", title: "Ron Mandatario Solera 700 ml", seller: "Mandatario", category: "Ron", url: "https://app.wong.pe/cervezas-vinos-y-licores/mandatario/40352", imageUrl: null, regularPrice: 79.9, currentPrice: 64.9, currency: "PEN", inStock: true, rating: null, reviewCount: null, observedAt: "2026-08-28T19:00:00.000Z" },
    { id: "bdl-l10", source: "Vivanda", domain: "vivanda.com.pe", title: "Ron Mandatario Solera 700 ml", seller: "Mandatario", category: "Ron", url: "https://www.vivanda.com.pe/ron-mandatario-solera-botella-700ml/p", imageUrl: null, regularPrice: 74.9, currentPrice: 74.9, currency: "PEN", inStock: true, rating: null, reviewCount: null, observedAt: "2026-08-28T19:00:00.000Z" },
    { id: "bdl-l11", source: "Tottus Perú", domain: "tottus.com.pe", title: "Ron Mandatario Solera 750 ml", seller: "Mandatario", category: "Ron", url: "https://www.tottus.com.pe/tottus-pe/marca/MANDATARIO", imageUrl: null, regularPrice: 79.9, currentPrice: 68.9, currency: "PEN", inStock: true, rating: null, reviewCount: null, observedAt: "2026-08-28T19:00:00.000Z" },
    { id: "bdl-l12", source: "Tottus Perú", domain: "tottus.com.pe", title: "Vino E. Copello Tinto Semiseco 750 ml", seller: "E. Copello", category: "Vino", url: "https://www.tottus.com.pe/tottus-pe/marca/E.COPELLO", imageUrl: null, regularPrice: 15.9, currentPrice: 13.9, currency: "PEN", inStock: true, rating: null, reviewCount: null, observedAt: "2026-08-28T19:00:00.000Z" },
    { id: "bdl-l13", source: "Metro Perú", domain: "metro.pe", title: "Vino Tinto Semiseco Blend E. Copello 750 ml", seller: "E. Copello", category: "Vino", url: "https://www.metro.pe/vino-tinto-semiseco-blend-e-copello-750ml-2/p", imageUrl: null, regularPrice: 15.9, currentPrice: 15.9, currency: "PEN", inStock: true, rating: null, reviewCount: null, observedAt: "2026-08-28T19:00:00.000Z" },
    { id: "bdl-l14", source: "Tottus Perú", domain: "tottus.com.pe", title: "Vino E. Copello Blanco Moscato 750 ml", seller: "E. Copello", category: "Vino", url: "https://www.tottus.com.pe/tottus-pe/articulo/113368517/vino-ecopello-blanco-moscato-botella-750-ml", imageUrl: null, regularPrice: 15.9, currentPrice: 13.9, currency: "PEN", inStock: true, rating: null, reviewCount: null, observedAt: "2026-08-28T19:00:00.000Z" },
    { id: "bdl-l15", source: "Metro Perú", domain: "metro.pe", title: "Vino Blanco Semiseco Moscato E. Copello 750 ml", seller: "E. Copello", category: "Vino", url: "https://www.metro.pe/vino-blanco-semiseco-moscato-e-copello-750ml-2/p", imageUrl: null, regularPrice: 15.9, currentPrice: 15.9, currency: "PEN", inStock: true, rating: null, reviewCount: null, observedAt: "2026-08-28T19:00:00.000Z" },
    { id: "bdl-l16", source: "Tottus Perú", domain: "tottus.com.pe", title: "Vino Casas Patronales Carmenere 750 ml", seller: "Casas Patronales", category: "Vino", url: "https://www.tottus.com.pe/tottus-pe/marca/CASAS%20PATRONALES", imageUrl: null, regularPrice: 39.9, currentPrice: 37.9, currency: "PEN", inStock: true, rating: null, reviewCount: null, observedAt: "2026-08-28T19:00:00.000Z" },
    { id: "bdl-l17", source: "Wong", domain: "wong.pe", title: "Vino Casas Patronales Gran Reserva Cabernet Sauvignon 750 ml", seller: "Casas Patronales", category: "Vino", url: "https://app.wong.pe/cervezas-vinos-y-licores/vinos/Cabernet%20Sauvignon/de-50-a-75/29585", imageUrl: null, regularPrice: 74.9, currentPrice: 66.9, currency: "PEN", inStock: true, rating: null, reviewCount: null, observedAt: "2026-08-28T19:00:00.000Z" },
    { id: "bdl-l18", source: "Tottus Perú", domain: "tottus.com.pe", title: "Vino Lagarde Cabernet Sauvignon 750 ml", seller: "Lagarde", category: "Vino", url: "https://www.tottus.com.pe/tottus-pe/marca/LAGARDE", imageUrl: null, regularPrice: 58.9, currentPrice: 58.9, currency: "PEN", inStock: true, rating: null, reviewCount: null, observedAt: "2026-08-28T19:00:00.000Z" },
  ],
  lastRun: {
    status: "demo_publica_verificada",
    sourcesAttempted: 5,
    sourcesSucceeded: 5,
    listingsFound: 18,
    productsFound: 7,
    startedAt: "2026-08-28T18:30:00.000Z",
    finishedAt: "2026-08-28T19:00:00.000Z",
    notes: "Demo comercial para Bodegas Don Luis construida con referencias públicas observadas en supermercados peruanos.",
  },
  live: {
    status: "live",
    mode: "persisted",
    freshness: "fresh",
    sourcePolicy: "public-demo",
    category: "Pisco · Ron · Vino",
    subjectBrand: "Bodegas Don Luis",
    competitorBrand: "Benchmark mercado Perú",
    channel: "Supermercados",
    market: "Perú",
    observedAt: "2026-08-28T19:00:00.000Z",
    sources: [
      {
        role: "brand",
        brand: "Bodegas Don Luis",
        channel: "Tottus · Metro · Wong · Vivanda · Plaza Vea/Makro",
        location: "Perú",
        url: "https://www.bodegasdonluis.pe/",
        domain: "bodegasdonluis.pe",
        status: "ok",
        observedAt: "2026-08-28T19:00:00.000Z",
        metrics: { items: 5, promoItems: 4, lowestPrice: 13.9, maxDiscountPct: 20 },
        error: null,
        items: [
          { key: "cg-q", name: "Cuatro Gallos Quebranta 700 ml", category: "Pisco", marketCategory: "Pisco", currentPrice: 38.9, regularPrice: 44.9, discountPct: 13.4, units: null, unitPrice: 55.57, benchmark: "pen-l", benchmarkLabel: "S/ por litro" },
          { key: "mand-sol", name: "Mandatario Solera", category: "Ron", marketCategory: "Ron", currentPrice: 68.9, regularPrice: 79.9, discountPct: 13.8, units: null, unitPrice: 91.87, benchmark: "pen-l", benchmarkLabel: "S/ por litro" },
          { key: "eco-tinto", name: "E. Copello Tinto Semiseco 750 ml", category: "Vino", marketCategory: "Vino", currentPrice: 13.9, regularPrice: 15.9, discountPct: 12.6, units: null, unitPrice: 18.53, benchmark: "pen-l", benchmarkLabel: "S/ por litro" },
          { key: "cp-carm", name: "Casas Patronales Carmenere 750 ml", category: "Vino", marketCategory: "Vino premium", currentPrice: 37.9, regularPrice: 39.9, discountPct: 5, units: null, unitPrice: 50.53, benchmark: "pen-l", benchmarkLabel: "S/ por litro" },
          { key: "lag-cab", name: "Lagarde Cabernet Sauvignon 750 ml", category: "Vino", marketCategory: "Vino premium", currentPrice: 58.9, regularPrice: null, discountPct: null, units: null, unitPrice: 78.53, benchmark: "pen-l", benchmarkLabel: "S/ por litro" },
        ],
      },
      {
        role: "competitor",
        brand: "Benchmark mercado Perú",
        channel: "Tottus",
        location: "Perú",
        url: "https://www.tottus.com.pe/tottus-pe/lista/CATG16069/Bebidas-Alcoholicas",
        domain: "tottus.com.pe",
        status: "ok",
        observedAt: "2026-08-28T19:00:00.000Z",
        metrics: { items: 4, promoItems: 4, lowestPrice: 14.9, maxDiscountPct: 25 },
        error: null,
        items: [
          { key: "sq-q", name: "Santiago Queirolo Quebranta 750 ml", category: "Pisco", marketCategory: "Pisco", currentPrice: 26.5, regularPrice: 35.5, discountPct: 25.4, units: null, unitPrice: 35.33, benchmark: "pen-l", benchmarkLabel: "S/ por litro" },
          { key: "fr-mv", name: "Finca Rotondo Mosto Verde Quebranta 750 ml", category: "Pisco", marketCategory: "Pisco premium", currentPrice: 56.9, regularPrice: 67.9, discountPct: 16.2, units: null, unitPrice: 75.87, benchmark: "pen-l", benchmarkLabel: "S/ por litro" },
          { key: "sq-vino", name: "Santiago Queirolo Magdalena 750 ml", category: "Vino", marketCategory: "Vino", currentPrice: 14.9, regularPrice: 17.9, discountPct: 16.8, units: null, unitPrice: 19.87, benchmark: "pen-l", benchmarkLabel: "S/ por litro" },
          { key: "fdc12", name: "Flor de Caña 12 Años 750 ml", category: "Ron", marketCategory: "Ron premium", currentPrice: 99.9, regularPrice: 119.9, discountPct: 16.7, units: null, unitPrice: 133.2, benchmark: "pen-l", benchmarkLabel: "S/ por litro" },
        ],
      },
    ],
    benchmarks: [
      { key: "pisco-mainstream", label: "Pisco · Cuatro Gallos vs Santiago Queirolo", subject: { brand: "Cuatro Gallos", price: 38.5, unitPrice: 55.0 }, competitor: { brand: "Santiago Queirolo", price: 26.5, unitPrice: 35.33 }, gapPct: 55.7, leader: "Santiago Queirolo", note: "Cuatro Gallos opera con un premium relevante frente a una referencia mainstream de Tottus; normalizado por litro." },
      { key: "pisco-premium", label: "Pisco · Cuatro Gallos vs Finca Rotondo MV", subject: { brand: "Cuatro Gallos", price: 38.5, unitPrice: 55.0 }, competitor: { brand: "Finca Rotondo", price: 56.9, unitPrice: 75.87 }, gapPct: -27.5, leader: "Cuatro Gallos", note: "Frente a una referencia premium de pisco, Cuatro Gallos queda aproximadamente 27,5% por debajo en precio por litro." },
      { key: "vino-entry", label: "Vino · E. Copello vs Santiago Queirolo", subject: { brand: "E. Copello", price: 13.9, unitPrice: 18.53 }, competitor: { brand: "Santiago Queirolo", price: 14.9, unitPrice: 19.87 }, gapPct: -6.7, leader: "E. Copello", note: "E. Copello aparece ligeramente por debajo de una referencia nacional de entrada, con espacio para evaluar elasticidad." },
      { key: "ron-premium", label: "Ron · Mandatario Solera vs Flor de Caña 12", subject: { brand: "Mandatario", price: 68.9, unitPrice: 91.87 }, competitor: { brand: "Flor de Caña 12", price: 99.9, unitPrice: 133.2 }, gapPct: -31.0, leader: "Mandatario", note: "Referencia de posicionamiento premium, no equivalencia exacta de añejamiento. Sirve para ubicar la escalera de precio." },
    ],
    history: {
      policy: "public-demo",
      days: 1,
      from: "2026-08-28",
      to: "2026-08-28",
      categories: ["Pisco · S/ por litro", "Ron · S/ por litro", "Vino · S/ por litro"],
      points: [
        { date: "2026-08-28", brand: "Bodegas Don Luis", role: "brand", category: "Pisco · S/ por litro", avgPrice: 55.0, avgUnitPrice: 55.0, minPrice: 55.0, maxPrice: 55.0, products: 1 },
        { date: "2026-08-28", brand: "Benchmark mercado Perú", role: "competitor", category: "Pisco · S/ por litro", avgPrice: 55.6, avgUnitPrice: 55.6, minPrice: 35.33, maxPrice: 75.87, products: 2 },
        { date: "2026-08-28", brand: "Bodegas Don Luis", role: "brand", category: "Ron · S/ por litro", avgPrice: 91.87, avgUnitPrice: 91.87, minPrice: 91.87, maxPrice: 91.87, products: 1 },
        { date: "2026-08-28", brand: "Benchmark mercado Perú", role: "competitor", category: "Ron · S/ por litro", avgPrice: 133.2, avgUnitPrice: 133.2, minPrice: 133.2, maxPrice: 133.2, products: 1 },
        { date: "2026-08-28", brand: "Bodegas Don Luis", role: "brand", category: "Vino · S/ por litro", avgPrice: 18.53, avgUnitPrice: 18.53, minPrice: 18.53, maxPrice: 18.53, products: 1 },
        { date: "2026-08-28", brand: "Benchmark mercado Perú", role: "competitor", category: "Vino · S/ por litro", avgPrice: 19.87, avgUnitPrice: 19.87, minPrice: 19.87, maxPrice: 19.87, products: 1 },
      ],
    },
  },
} as const;
