import LegalPage from "../LegalPage";
import styles from "../legal.module.css";

export const metadata = { title: "Uso responsable de datos | MGP Super Precios", description: "Política de uso responsable de datos e inteligencia competitiva." };

export default function DataUsePage(){return <LegalPage title="Uso responsable de datos" intro="Principios para utilizar información de precios, promociones, surtido e inteligencia competitiva de manera legítima, segura y responsable.">
  <div className={styles.warning}>MGP Super Precios es una herramienta de análisis. No debe utilizarse para coordinar precios, intercambiar información comercial confidencial entre competidores ni facilitar acuerdos o prácticas que restrinjan la libre competencia.</div>
  <section><h2>1. Finalidad legítima</h2><p>La información y herramientas de la plataforma están destinadas a análisis competitivo independiente, planificación comercial, pricing, marketing, category management, surtido, disponibilidad, benchmarking y reportes internos.</p></section>
  <section><h2>2. Libre competencia</h2><p>Los usuarios deben tomar decisiones de manera unilateral e independiente. Está prohibido utilizar MGP Super Precios como mecanismo para acordar, coordinar o señalar a competidores precios futuros, condiciones comerciales, cuotas, territorios, producción, licitaciones u otras variables competitivas.</p><p>El hecho de observar información pública del mercado no sustituye las obligaciones de cada organización bajo las normas de libre competencia.</p></section>
  <section><h2>3. Información confidencial y personal</h2><ul><li>No ingreses secretos comerciales de terceros si no cuentas con autorización.</li><li>No cargues datos personales sensibles que no sean necesarios para utilizar el producto.</li><li>No uses la plataforma para identificar, perfilar o perseguir personas naturales a partir de información que no corresponde al propósito del servicio.</li><li>Si conectas datos propios, asegúrate de contar con una base legal, contractual o autorización adecuada para procesarlos.</li></ul></section>
  <section><h2>4. Inteligencia artificial responsable</h2><p>Las respuestas generadas por IA deben interpretarse como apoyo analítico. No deben ejecutarse automáticamente como decisiones de precio, contratación, exclusión de proveedores o acciones que puedan producir consecuencias legales o comerciales relevantes sin revisión humana.</p><p>El usuario debe revisar la fuente, fecha, comparabilidad y contexto antes de utilizar un insight en decisiones sensibles.</p></section>
  <section><h2>5. Exportaciones y redistribución</h2><p>Las exportaciones están destinadas al uso autorizado de la organización contratante. No se permite revender, publicar masivamente, sublicenciar o reconstruir un servicio competidor a partir de exportaciones de MGP sin autorización expresa.</p></section>
  <section><h2>6. Uso abusivo</h2><p>Podemos limitar o suspender una cuenta cuando existan indicios razonables de extracción automatizada abusiva, evasión de límites, acceso no autorizado, uso ilícito o riesgo para otros clientes, fuentes o infraestructura.</p></section>
  <section><h2>7. Consultas</h2><p>Si tu caso de uso involucra intercambio de información entre competidores, datos personales a gran escala o decisiones de alto impacto, recomendamos obtener revisión jurídica o de compliance independiente antes de implementarlo.</p><div className={styles.contact}><strong>Contacto MGP</strong><a href="mailto:sebastian@mgpconsultoria.cl">sebastian@mgpconsultoria.cl</a><a href="tel:+56982315934">+56 9 8231 5934</a></div></section>
</LegalPage>}
