import {NextRequest,NextResponse} from "next/server";
import {enterpriseAccess} from "@/lib/enterprise-auth";
import {clickHouseConfigured} from "@/lib/clickhouse";
import {clickHouseInsight} from "@/lib/clickhouse-insights";
import {clickHouseInsightV2,insightV2BrandOptions,type InsightV2Mode} from "@/lib/clickhouse-insights-v2";
import {fullHistoryProductOptions} from "@/lib/clickhouse-full-history-products";
import {fullHistoryEvolution} from "@/lib/clickhouse-full-history-evolution";
import {fullHistoryAlerts} from "@/lib/clickhouse-full-history-alerts";
export const dynamic="force-dynamic";export const revalidate=0;
const V2=new Set<InsightV2Mode>(["price-evolution","price-gaps","price-alerts","products","data-status"]);
function days(v:string|null){const n=Number(v??30);return[7,30,90,180].includes(n)?n:30}
export async function GET(req:NextRequest){const auth=await enterpriseAccess(req,"overview");if(auth.response)return auth.response;if(!auth.access)return NextResponse.json({error:"No fue posible resolver el acceso enterprise."},{status:500});if(!clickHouseConfigured())return NextResponse.json({error:"ClickHouse no está configurado.",source:"clickhouse"},{status:503});const p=req.nextUrl.searchParams;try{if(p.get("options")==="brands")return NextResponse.json({source:"clickhouse",brands:await insightV2BrandOptions(auth.access)},{headers:{"cache-control":"private, max-age=300, stale-while-revalidate=900"}});if(p.get("options")==="products")return NextResponse.json({source:"clickhouse",products:await fullHistoryProductOptions(auth.access,p.get("brand")??"",days(p.get("days")))},{headers:{"cache-control":"private, max-age=60, stale-while-revalidate=180"}});const raw=(p.get("mode")??"price-evolution") as InsightV2Mode;const f={brand:p.get("brand"),productId:p.get("productId"),days:days(p.get("days"))};if(raw==="price-evolution")return NextResponse.json({source:"clickhouse",mode:raw,generatedAt:new Date().toISOString(),...await fullHistoryEvolution(auth.access,f)},{headers:{"cache-control":"private, max-age=20, stale-while-revalidate=90"}});if(raw==="price-alerts")return NextResponse.json({source:"clickhouse",mode:raw,generatedAt:new Date().toISOString(),...await fullHistoryAlerts(auth.access,f)},{headers:{"cache-control":"private, max-age=20, stale-while-revalidate=90"}});if(V2.has(raw))return NextResponse.json(await clickHouseInsightV2(auth.access,raw,{...f,query:p.get("q"),page:Number(p.get("page")??1),pageSize:Number(p.get("pageSize")??60)}),{headers:{"cache-control":"private, max-age=20, stale-while-revalidate=90"}});const legacy=p.get("mode")==="market-coverage"?"market-coverage":"retailer-benchmark";return NextResponse.json(await clickHouseInsight(auth.access,legacy,{brand:p.get("brand"),product:null,days:days(p.get("days"))}),{headers:{"cache-control":"private, max-age=30, stale-while-revalidate=120"}})}catch(e){console.error("clickhouse-insight-v2",e);return NextResponse.json({error:"No fue posible cargar el análisis desde ClickHouse.",source:"clickhouse"},{status:503})}}
