import { strict as assert } from "node:assert";
import { parseNissanGuillermoMorales, discoverNissanGuillermoMorales } from "./nissan-parser.ts";
const base = "https://guillermomorales.cl/autos-nuevos/nissan";
const row = (label: string, a: number, b: number) => `<tr><td>${label}</td><td>$${a}<label>${label}</label></td><td>$${b}</td></tr>`;
const table = (extra = "", finance = true) => `<table><tr><th><select data-tipo="precio"><option selected value="1">SENSE MT</option><option value="2">SENSE CVT</option></select></th><th><select data-tipo="precio"><option value="1">SENSE MT</option><option selected value="2">SENSE CVT</option></select></th></tr>${row("Precio Lista",16990000,17990000)}${finance ? row("Bono Financiamiento",1500000,1500000) : ""}${row("Bono Todo Medio Pago",2000000,1500000)}${row("Precio Desde",finance ? 13490000 : 14990000,finance ? 14990000 : 16490000)}${extra}</table>`;
const parse = (html: string) => parseNissanGuillermoMorales(html, `${base}/versa`, "nissan_gm", "Guillermo Morales");
const versions = parse(table());
assert.equal(versions.length,2);
assert.equal(versions[1].version,"SENSE CVT");
assert.equal(versions[0].cash_price,14990000);
assert.equal(versions[0].final_price,13490000);
assert.equal(versions[0].metadata.advertised_price_reconciled,true);
assert.equal(parse(table("",false))[0].metadata.final_price_condition,"all_payment_methods");
assert.equal(parse(table(row("BonoGM",500000,0)))[0].cash_price,null);
assert.equal(parse(table(row("BonoGM",500000,0)))[0].metadata.advertised_price_reconciled,false);
assert.equal(parseNissanGuillermoMorales(table(),base,"nissan_gm","GM").length,0);
const links = `<a href="${base}/versa">a</a><a href="${base}/versa">b</a><a href="https://evil.example/autos-nuevos/nissan/versa">x</a><a href="/autos-nuevos/kia/sportage">x</a>`;
assert.equal(discoverNissanGuillermoMorales(links,base,"root").length,1);
assert.equal(discoverNissanGuillermoMorales(links,base,"model").length,0);
console.log("Nissan parser: price scenarios, version identities, duplicate discovery and domain boundaries passed");
