import LegalPage from "../LegalPage";
import styles from "../legal.module.css";

export const metadata = { title: "Términos de uso | MGP Super Precios", description: "Términos generales de uso de MGP Super Precios." };

export default function TermsPage(){return <LegalPage title="Términos de uso" intro="Condiciones generales para acceder, probar y utilizar MGP Super Precios. Los términos comerciales específicos de un cliente pueden complementarse mediante una propuesta, orden de compra o contrato separado.">
  <section><h2>1. Alcance</h2><p>Estos términos regulan el acceso a la web, cuentas trial y plataforma MGP Super Precios. Al crear una cuenta o utilizar el servicio, declaras que tienes capacidad y autorización suficiente para actuar por ti o por la organización que representas.</p></section>
  <section><h2>2. Cuentas y credenciales</h2><p>Cada usuario debe mantener sus credenciales bajo control y usar una identidad real y autorizada. No se permite compartir cuentas de forma que eluda límites de usuarios, controles de acceso o condiciones comerciales.</p><p>Podemos bloquear o suspender accesos cuando existan indicios razonables de abuso, riesgo de seguridad, incumplimiento grave, impago o vencimiento del trial.</p></section>
  <section><h2>3. Trials y planes</h2><p>Los trials se entregan para evaluación del producto y pueden estar sujetos a límites de tiempo, usuarios, retailers, exportaciones y módulos. La disponibilidad de determinadas funciones durante un trial no implica que queden incluidas en un plan pagado.</p><p>Los precios, alcances, descuentos, vigencias y condiciones de facturación aplicables serán los indicados en la página de precios, propuesta comercial u orden contractual vigente para cada cliente.</p></section>
  <section><h2>4. Uso permitido</h2><p>El servicio debe utilizarse para fines legítimos de análisis, inteligencia comercial, pricing, marketing, categoría, surtido, disponibilidad, reportes y actividades relacionadas. El usuario es responsable de que sus decisiones y acciones cumplan la legislación aplicable.</p><p>No se permite utilizar la plataforma para acceder sin autorización a sistemas de terceros, vulnerar derechos, cargar contenido ilícito, eludir controles técnicos, extraer masivamente el servicio para revenderlo sin autorización, ni realizar actividades destinadas a afectar su disponibilidad o seguridad.</p></section>
  <section><h2>5. Inteligencia artificial</h2><p>Las funciones de IA generan análisis a partir de datos y contexto disponible, pero pueden contener errores, omisiones o interpretaciones incompletas. Las respuestas no constituyen asesoría legal, financiera ni una instrucción automática de fijación de precios. El usuario debe validar decisiones críticas con sus propios criterios y fuentes.</p></section>
  <section><h2>6. Datos de mercado</h2><p>Los precios, promociones, disponibilidad y demás señales de mercado pueden provenir de fuentes públicas y cambiar después de su captura. MGP Super Precios busca mantener información actualizada y útil, pero no garantiza que cada observación represente el precio final disponible para toda persona, ubicación o momento.</p></section>
  <section><h2>7. Propiedad intelectual</h2><p>La plataforma, interfaces, software, modelos, documentación, diseño, reportes y elementos propios de MGP están protegidos por las normas aplicables. Las marcas y contenidos de terceros pertenecen a sus respectivos titulares.</p><p>La contratación del servicio otorga un derecho de uso limitado al cliente conforme a su plan; no transfiere la propiedad del software ni autoriza su copia, ingeniería inversa, sublicencia o distribución salvo acuerdo expreso.</p></section>
  <section><h2>8. Disponibilidad y soporte</h2><p>Trabajamos para mantener el servicio disponible y confiable, pero pueden existir mantenciones, fallas de proveedores, cambios en sitios fuente u otros eventos fuera de control razonable. Un SLA específico solo será exigible cuando haya sido acordado expresamente por escrito.</p></section>
  <section><h2>9. Modificaciones</h2><p>Podemos actualizar estos términos para reflejar cambios legales, técnicos o comerciales. La versión publicada indicará su fecha de actualización. Los cambios materiales que afecten contratos vigentes se aplicarán conforme al acuerdo correspondiente y la normativa aplicable.</p></section>
  <section><h2>10. Contacto</h2><div className={styles.contact}><strong>MGP Super Precios</strong><a href="mailto:sebastian@mgpconsultoria.cl">sebastian@mgpconsultoria.cl</a><a href="tel:+56982315934">+56 9 8231 5934</a><span>Chile</span></div></section>
</LegalPage>}
