"use client";

import { useEffect, useMemo, useState } from "react";
import styles from "./ClickHouseInsightView.module.css";

export type ClickHouseInsightMode = "price-evolution"|"retailer-benchmark"|"market-coverage"|"price-gaps"|"price-alerts"|"products"|"data-status";
type BrandOption={value:string;products:number};
type ProductOption={id:string;name:string;brand:string;retailer:string;latestPrice:number;lastObservedAt:string|null;availableDays?:number};
type EvolutionSeries={retailer:string;points:Array<{date:string;price:number;products:number}>};
type Retailer={retailer:string;products:number;medianPrice:number;averagePrice:number;minPrice:number;maxPrice:number;inStock:number;availabilityPct:number;lastObservedAt:string|null};
type Gap={brand:string;category:string;retailers:number;products:number;lowRetailer:string;highRetailer:string;lowPrice:number;highPrice:number;gapPct:number};
type Alert={id:string;name:string;brand:string|null;category:string|null;retailer:string;vertical:string;previousPrice:number;currentPrice:number;previousDate:string;currentDate:string;changePct:number;priceDelta:number;observedAt:string|null};
type Product={id:string;name:string;brand:string|null;category:string|null;retailer:string;vertical?:string;price:number;regularPrice:number;inStock:boolean;observedAt:string|null;url:string};
type DataStatus={retailer:string;vertical?:string;products:number;latestObservedAt:string|null;observations24h:number};
type Payload={source:"clickhouse";mode:ClickHouseInsightMode;generatedAt:string;series?:EvolutionSeries[];retailers?:Retailer[]|DataStatus[];gaps?:Gap[];alerts?:Alert[];products?:Product[];total?:number;page?:number;pageSize?:number;totalPages?:number;error?:string};

const COLORS=["#f5c400","#4f9cf9","#60c77a","#d978e8","#f08154","#63d5d1","#a78bfa","#e5e7eb"];
const moneyFormat=new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0});
const integer=new Intl.NumberFormat("es-CL",{maximumFractionDigits:0});
const compact=new Intl.NumberFormat("es-CL",{notation:"compact",maximumFractionDigits:1});
const META:Record<ClickHouseInsightMode,{eyebrow:string;title:string;copy:string}>={
 "price-evolution":{eyebrow:"PRICE EVOLUTION",title:"Evolución de precios",copy:"Histórico real por fecha, retailer y producto. Los productos disponibles tienen data dentro del período elegido."},
 "retailer-benchmark":{eyebrow:"RETAILER BENCHMARK",title:"Benchmark por retailer",copy:"Compara mediana, rango de precios y cobertura entre retailers."},
 "market-coverage":{eyebrow:"MARKET COVERAGE",title:"Cobertura de mercado",copy:"Profundidad y disponibilidad del universo seleccionado."},
 "price-gaps":{eyebrow:"PRICE GAPS",title:"Brechas de precio",copy:"Muestra la principal brecha comparable de cada marca entre retailers."},
 "price-alerts":{eyebrow:"PRICE MOVEMENTS",title:"Movimientos y alertas",copy:"Movimientos relevantes usando las dos últimas fechas reales disponibles por SKU, en todas las verticales."},
 products:{eyebrow:"PRODUCT EXPLORER",title:"Productos",copy:"Busca sobre todo el catálogo de ClickHouse; los resultados se consultan server-side y no están limitados a 120 SKU."},
 "data-status":{eyebrow:"DATA STATUS",title:"Estado de datos",copy:"Freshness y cobertura de observaciones por retailer."},
};
function money(v:number){return moneyFormat.format(Number.isFinite(v)?v:0)}
function num(v:number){return integer.format(Number.isFinite(v)?v:0)}
function short(v:number){return compact.format(Number.isFinite(v)?v:0)}
function pct(v:number){return `${v>0?"+":""}${v.toFixed(1)}%`}
function shortDate(value:string){try{return new Intl.DateTimeFormat("es-CL",{day:"2-digit",month:"short"}).format(new Date(`${value}T12:00:00`)).replace(".","")}catch{return value}}
function verticalLabel(v:string|undefined){return v==="supermarket"?"Supermercado":v==="department_store"?"Multitienda":v==="pharmacy"?"Farmacia":v==="home_improvement"?"Home Improvement":v||"Retail"}
function timeAgo(value:string|null|undefined){if(!value)return"sin datos";const delta=Date.now()-new Date(value).getTime();if(!Number.isFinite(delta)||delta<60000)return"ahora";const m=Math.floor(delta/60000);if(m<60)return`hace ${m} min`;const h=Math.floor(m/60);if(h<24)return`hace ${h} h`;return`hace ${Math.floor(h/24)} d`}
function Empty({text}:{text:string}){return <div className={styles.empty}>{text}</div>}

function EvolutionChart({series}:{series:EvolutionSeries[]}){
 const dates=[...new Set(series.flatMap((x)=>x.points.map((p)=>p.date)))].sort();const values=series.flatMap((x)=>x.points.map((p)=>p.price)).filter((v)=>v>0);if(!dates.length||!values.length)return <Empty text="No hay histórico para este producto dentro del período seleccionado."/>;
 const width=960,height=350,margin={top:22,right:22,bottom:48,left:72},pw=width-margin.left-margin.right,ph=height-margin.top-margin.bottom,rawMin=Math.min(...values),rawMax=Math.max(...values),pad=Math.max(1,(rawMax-rawMin)*.15,rawMax*.02),min=Math.max(0,rawMin-pad),max=rawMax+pad,x=(i:number)=>margin.left+i/Math.max(1,dates.length-1)*pw,y=(v:number)=>margin.top+(max-v)/Math.max(1,max-min)*ph;
 return <div className={styles.chartWrap}><svg viewBox={`0 0 ${width} ${height}`} className={styles.lineChart}>{[0,1,2,3,4].map((i)=>{const v=max-i*(max-min)/4,yy=y(v);return <g key={i}><line x1={margin.left} x2={width-margin.right} y1={yy} y2={yy}/><text x={margin.left-12} y={yy+4}>{money(v)}</text></g>})}{series.slice(0,8).map((item,index)=>{const map=new Map(item.points.map((p)=>[p.date,p.price]));let drawing=false;const path=dates.map((date,i)=>{const v=map.get(date);if(!v){drawing=false;return""}const cmd=drawing?"L":"M";drawing=true;return`${cmd}${x(i).toFixed(1)},${y(v).toFixed(1)}`}).join(" ");return <path key={item.retailer} d={path} style={{stroke:COLORS[index%COLORS.length]}}/>})}{dates.filter((_,i)=>i===0||i===dates.length-1||i%Math.max(1,Math.floor(dates.length/5))===0).map((date)=><text className={styles.xLabel} key={date} x={x(dates.indexOf(date))} y={height-12}>{shortDate(date)}</text>)}</svg><div className={styles.legend}>{series.slice(0,8).map((item,index)=><span key={item.retailer}><i style={{background:COLORS[index%COLORS.length]}}/>{item.retailer}</span>)}</div></div>
}
function RetailerBars({rows,coverage=false}:{rows:Retailer[];coverage?:boolean}){if(!rows.length)return <Empty text="No hay retailers con datos para este filtro."/>;const sorted=[...rows].sort((a,b)=>coverage?b.products-a.products:a.medianPrice-b.medianPrice),max=Math.max(...sorted.map((r)=>coverage?r.products:r.medianPrice),1);return <div className={styles.horizontalBars}>{sorted.map((r,i)=>{const v=coverage?r.products:r.medianPrice;return <div key={r.retailer} className={styles.horizontalRow}><header><strong>{r.retailer}</strong><span>{coverage?`${short(r.products)} SKU`:money(r.medianPrice)}</span></header><div><i style={{width:`${Math.max(5,v/max*100)}%`,background:i===0?"#f5c400":undefined}}/></div><footer>{coverage?`${r.availabilityPct.toFixed(1)}% disponibilidad`:`${short(r.products)} SKU · ${r.availabilityPct.toFixed(1)}% disponibilidad`}</footer></div>})}</div>}

export default function ClickHouseInsightView({mode}:{mode:ClickHouseInsightMode}){
 const[brands,setBrands]=useState<BrandOption[]>([]),[brand,setBrand]=useState(""),[options,setOptions]=useState<ProductOption[]>([]),[product,setProduct]=useState(""),[days,setDays]=useState(30),[payload,setPayload]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[filterLoading,setFilterLoading]=useState(false),[error,setError]=useState(""),[catalogQuery,setCatalogQuery]=useState(""),[debouncedQuery,setDebouncedQuery]=useState(""),[catalogPage,setCatalogPage]=useState(1);
 const meta=META[mode];
 useEffect(()=>{const t=window.setTimeout(()=>setDebouncedQuery(catalogQuery.trim()),250);return()=>window.clearTimeout(t)},[catalogQuery]);
 useEffect(()=>{setCatalogPage(1)},[debouncedQuery,brand]);
 useEffect(()=>{const key="mgp_ch_brands_v2",cached=window.sessionStorage.getItem(key);if(cached){try{setBrands(JSON.parse(cached));return}catch{}}const c=new AbortController();fetch("/api/clickhouse-insight-v2?options=brands",{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"No fue posible cargar marcas");setBrands(d.brands??[]);window.sessionStorage.setItem(key,JSON.stringify(d.brands??[]))}).catch(e=>{if(!(e instanceof DOMException&&e.name==="AbortError"))setError(e instanceof Error?e.message:"No fue posible cargar marcas")});return()=>c.abort()},[]);
 useEffect(()=>{setProduct("");setOptions([]);if(!brand||mode!=="price-evolution")return;const key=`mgp_ch_products_v2:${brand}:${days}`,cached=window.sessionStorage.getItem(key);if(cached){try{setOptions(JSON.parse(cached));return}catch{}}const c=new AbortController();setFilterLoading(true);fetch(`/api/clickhouse-insight-v2?options=products&brand=${encodeURIComponent(brand)}&days=${days}`,{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"No fue posible cargar productos");setOptions(d.products??[]);window.sessionStorage.setItem(key,JSON.stringify(d.products??[]))}).catch(e=>{if(!(e instanceof DOMException&&e.name==="AbortError"))setError(e instanceof Error?e.message:"No fue posible cargar productos")}).finally(()=>setFilterLoading(false));return()=>c.abort()},[brand,days,mode]);
 useEffect(()=>{const c=new AbortController(),p=new URLSearchParams({mode,days:String(days)});if(brand)p.set("brand",brand);const selected=options.find((x)=>x.id===product);if(selected)p.set("productId",selected.id);if(mode==="products"){if(debouncedQuery)p.set("q",debouncedQuery);p.set("page",String(catalogPage));p.set("pageSize","60")}setLoading(true);setError("");fetch(`/api/clickhouse-insight-v2?${p}`,{signal:c.signal}).then(async r=>{const d=await r.json() as Payload;if(!r.ok||d.source!=="clickhouse")throw new Error(d.error||"No fue posible cargar ClickHouse");setPayload(d)}).catch(e=>{if(!(e instanceof DOMException&&e.name==="AbortError"))setError(e instanceof Error?e.message:"No fue posible cargar el análisis")}).finally(()=>setLoading(false));return()=>c.abort()},[mode,brand,product,days,options,debouncedQuery,catalogPage]);
 const selected=options.find((x)=>x.id===product),retailers=(payload?.retailers??[]) as Retailer[],status=(payload?.retailers??[]) as DataStatus[];
 const summary=useMemo(()=>{if(mode==="retailer-benchmark"||mode==="market-coverage"){const total=retailers.reduce((s,r)=>s+r.products,0),median=retailers.length?[...retailers].sort((a,b)=>a.medianPrice-b.medianPrice)[Math.floor(retailers.length/2)]?.medianPrice??0:0;return[{label:"Retailers",value:num(retailers.length)},{label:"Productos",value:short(total)},{label:"Mediana",value:money(median)}]}if(mode==="price-alerts"){const r=payload?.alerts??[];return[{label:"Movimientos relevantes",value:num(r.length)},{label:"Bajas",value:num(r.filter(x=>x.changePct<0).length)},{label:"Alzas",value:num(r.filter(x=>x.changePct>0).length)}]}if(mode==="price-gaps"){const r=payload?.gaps??[];return[{label:"Marcas con brecha",value:num(r.length)},{label:"Mayor brecha",value:r.length?`${Math.max(...r.map(x=>x.gapPct)).toFixed(1)}%`:"—"},{label:"Universo",value:brand?brand:"Todas las marcas"}]}if(mode==="products"){const r=payload?.products??[];return[{label:"Catálogo encontrado",value:short(payload?.total??r.length)},{label:"Página",value:`${payload?.page??1} / ${payload?.totalPages??1}`},{label:"Retailers visibles",value:num(new Set(r.map(x=>x.retailer)).size)}]}if(mode==="data-status")return[{label:"Retailers",value:num(status.length)},{label:"Activos 24h",value:num(status.filter(r=>r.observations24h>0).length)},{label:"Productos",value:short(status.reduce((s,r)=>s+r.products,0))}];const r=payload?.series??[];return[{label:"Retailers",value:num(r.length)},{label:"Producto",value:selected?"1 SKU":"Agregado"},{label:"Período",value:`${days} días`} ]},[mode,payload,retailers,status,brand,selected,days]);
 return <section className={styles.root}><header className={styles.hero}><div><span>{meta.eyebrow}</span><h1>{meta.title}</h1><p>{meta.copy}</p></div><div className={styles.source}><i/>CLICKHOUSE LIVE</div></header>
  <section className={styles.filters} style={mode==="products"?{gridTemplateColumns:"minmax(180px,.8fr) minmax(320px,2fr) 110px"}:mode==="price-evolution"?undefined:{gridTemplateColumns:"minmax(220px,1fr) 150px 100px"}}>
   <label><span>Marca</span><select value={brand} onChange={e=>setBrand(e.target.value)}><option value="">Todas las marcas</option>{brands.map(x=><option key={x.value} value={x.value}>{x.value} · {short(x.products)}</option>)}</select></label>
   {mode==="price-evolution"&&<label className={styles.productFilter}><span>Producto con histórico en {days}d</span><select disabled={!brand||filterLoading} value={product} onChange={e=>setProduct(e.target.value)}><option value="">{!brand?"Selecciona primero una marca":filterLoading?"Cargando productos…":"Todos los productos de la marca"}</option>{options.map(x=><option key={x.id} value={x.id}>{x.name} · {x.retailer} · {money(x.latestPrice)} · {x.availableDays??0} días</option>)}</select></label>}
   {mode==="products"&&<label><span>Buscar en todo el catálogo</span><input value={catalogQuery} onChange={e=>setCatalogQuery(e.target.value)} placeholder="Producto, marca, categoría o retailer…" style={{height:40,border:"1px solid #2a333e",borderRadius:8,background:"#151b23",color:"#edf0f4",padding:"0 10px",outline:"none"}}/></label>}
   {mode!=="products"&&<label><span>Período</span><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 días</option><option value={30}>30 días</option><option value={90}>90 días</option><option value={180}>180 días</option></select></label>}
   <button onClick={()=>{setBrand("");setProduct("");setDays(30);setCatalogQuery("");setCatalogPage(1)}}>Limpiar</button>
  </section>
  {selected&&<div className={styles.context}><span>PRODUCTO ACTIVO</span><strong>{selected.brand} · {selected.name}</strong><em>{selected.retailer} · {selected.availableDays??0} días con observación</em></div>}
  {error&&<div className={styles.error}>{error}</div>}<section className={styles.kpis}>{summary.map(x=><article key={x.label}><span>{x.label}</span><strong>{x.value}</strong></article>)}</section><article className={styles.card}>{loading?<div className={styles.loading}><i/><span>Consultando ClickHouse…</span></div>:<InsightBody mode={mode} payload={payload}/>}</article>
  {mode==="products"&&(payload?.totalPages??1)>1&&<div style={{display:"flex",justifyContent:"center",alignItems:"center",gap:10,marginTop:12}}><button disabled={(payload?.page??1)<=1} onClick={()=>setCatalogPage(p=>Math.max(1,p-1))} style={{padding:"8px 14px",border:"1px solid #2a333e",borderRadius:8,background:"#151b23",color:"#fff"}}>← Anterior</button><span style={{fontSize:10,color:"#8994a3"}}>Página {payload?.page??1} de {payload?.totalPages??1} · {num(payload?.total??0)} productos</span><button disabled={(payload?.page??1)>=(payload?.totalPages??1)} onClick={()=>setCatalogPage(p=>p+1)} style={{padding:"8px 14px",border:"1px solid #2a333e",borderRadius:8,background:"#151b23",color:"#fff"}}>Siguiente →</button></div>}
  <footer className={styles.footer}>ClickHouse · consultas bajo demanda · sin límite artificial de 120 productos para búsqueda.</footer></section>
}

function InsightBody({mode,payload}:{mode:ClickHouseInsightMode;payload:Payload|null}){if(!payload)return <Empty text="Sin datos."/>;if(mode==="price-evolution")return <EvolutionChart series={payload.series??[]}/>;if(mode==="retailer-benchmark")return <RetailerBars rows={(payload.retailers??[]) as Retailer[]}/>;if(mode==="market-coverage")return <RetailerBars rows={(payload.retailers??[]) as Retailer[]} coverage/>;if(mode==="price-gaps"){const rows=payload.gaps??[];if(!rows.length)return <Empty text="No hay brechas comparables."/>;return <div className={styles.gapGrid}>{rows.map(r=><div key={`${r.brand}-${r.category}`}><header><span><b>{r.brand}</b><small>{r.category} · {short(r.products)} SKU · {r.retailers} retailers</small></span><em>+{r.gapPct.toFixed(1)}%</em></header><section><div><small>MENOR</small><strong>{money(r.lowPrice)}</strong><span>{r.lowRetailer}</span></div><i>→</i><div><small>MAYOR</small><strong>{money(r.highPrice)}</strong><span>{r.highRetailer}</span></div></section></div>)}</div>}
 if(mode==="price-alerts"){const rows=payload.alerts??[];if(!rows.length)return <Empty text="No encontramos dos observaciones comparables por SKU dentro del período."/>;const max=Math.max(...rows.map(r=>Math.abs(r.changePct)),1);return <div className={styles.alertList}>{rows.map(r=><div key={`${r.id}-${r.currentDate}`}><span className={r.changePct<0?styles.down:styles.up}>{r.changePct<0?"↓":"↑"}</span><section><strong>{r.name}</strong><small>{r.brand||"Sin marca"} · {r.category||"Sin categoría"} · {r.retailer} · {verticalLabel(r.vertical)}</small><i><em style={{width:`${Math.max(4,Math.abs(r.changePct)/max*100)}%`}}/></i></section><div><b>{pct(r.changePct)}</b><small>{money(r.previousPrice)} → {money(r.currentPrice)} · {shortDate(r.previousDate)} → {shortDate(r.currentDate)}</small></div></div>)}</div>}
 if(mode==="products"){const rows=payload.products??[];if(!rows.length)return <Empty text="No hay productos que coincidan con la búsqueda."/>;return <div className={styles.productGrid}>{rows.map(r=><a key={r.id} href={r.url} target="_blank" rel="noreferrer"><header><span>{r.brand||"Sin marca"}</span><em>{r.retailer}</em></header><strong>{r.name}</strong><small>{r.category||"Sin categoría"} · {verticalLabel(r.vertical)}</small><footer><b>{money(r.price)}</b><span className={r.inStock?styles.stock:styles.noStock}>{r.inStock?"Disponible":"Sin stock"}</span></footer></a>)}</div>}
 const rows=(payload.retailers??[]) as DataStatus[];if(!rows.length)return <Empty text="No hay fuentes para mostrar."/>;return <div className={styles.statusGrid}>{rows.map(r=><article key={r.retailer}><header><i className={r.observations24h>0?styles.live:styles.stale}/><strong>{r.retailer}</strong></header><b>{short(r.products)} productos</b><span>{verticalLabel(r.vertical)} · {short(r.observations24h)} actualizados en 24h</span><small>Última observación {timeAgo(r.latestObservedAt)}</small></article>)}</div>}
