"use client";
import { useEffect,useState } from "react";
import styles from "./VictorinoxMarketPanel.module.css";
type Point={date:string;ownMedian:number;benchmarkMedian:number;priceIndex:number;premiumPct:number};
type Category={category:string;points:Point[]};
type Data={categories:Category[];error?:string};
const money=new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0});
function d(v:string){return new Intl.DateTimeFormat("es-CL",{day:"2-digit",month:"short"}).format(new Date(v+"T12:00:00"));}
function Chart({item}:{item:Category}){const p=item.points;if(p.length<2)return <article className={styles.historyCard}><h3>{item.category}</h3><p>Histórico comparable en construcción.</p></article>;const vals=p.flatMap(x=>[x.ownMedian,x.benchmarkMedian]),min=Math.min(...vals)*.92,max=Math.max(...vals)*1.08,w=620,h=220,l=38,r=16,t=15,b=30;const x=(i:number)=>l+i/Math.max(1,p.length-1)*(w-l-r),y=(v:number)=>t+(max-v)/Math.max(1,max-min)*(h-t-b),path=(k:"ownMedian"|"benchmarkMedian")=>p.map((q,i)=>`${i?"L":"M"}${x(i)},${y(q[k])}`).join(" ");const last=p.at(-1)!;return <article className={styles.historyCard}><div><span>EVOLUCIÓN</span><h3>{item.category}</h3><small>Index {last.priceIndex.toFixed(1)} · Victorinox {money.format(last.ownMedian)} vs benchmark {money.format(last.benchmarkMedian)}</small></div><svg viewBox={`0 0 ${w} ${h}`}><path d={path("benchmarkMedian")} className={styles.historyBenchmark}/><path d={path("ownMedian")} className={styles.historyOwn}/><text x={l} y={h-6}>{d(p[0].date)}</text><text x={w-r} y={h-6} textAnchor="end">{d(last.date)}</text></svg></article>;}
export default function VictorinoxHistory({compact=false}:{compact?:boolean}){const[days,setDays]=useState(compact?30:90),[data,setData]=useState<Data|null>(null),[error,setError]=useState("");useEffect(()=>{const c=new AbortController();fetch(`/api/brands-competition-history-v3?days=${days}`,{signal:c.signal,credentials:"same-origin"}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);return j}).then(setData).catch(e=>{if(e.name!=="AbortError")setError(e.message)});return()=>c.abort();},[days]);return <section className={styles.historySection}><div className={styles.panelTitle}><div><span>HISTÓRICO COMPETITIVO</span><h2>Evolución Victorinox vs benchmark</h2><p>Mediana diaria de Victorinox contra mediana de las marcas competidoras.</p></div>{!compact&&<div className={styles.dayButtons}>{[30,90,180].map(x=><button key={x} className={days===x?styles.activeDay:""} onClick={()=>setDays(x)}>{x}D</button>)}</div>}</div>{error?<div className={styles.empty}>{error}</div>:!data?<div className={styles.empty}>Construyendo histórico…</div>:<div className={styles.historyGrid}>{data.categories.filter(x=>!compact||["Relojes","Equipo de viaje","Navajas y multiherramientas","Cuchillos"].includes(x.category)).map(x=><Chart key={x.category} item={x}/>)}</div>}</section>;}
