"use client";
import { useState,type ReactNode } from "react";
import styles from "./VictorinoxMarketPanel.module.css";
import { trackUsageEvent } from "@/lib/usage-client";
type Msg={role:"user"|"assistant";content:string};

function inline(text:string){const p=text.split(/(\*\*[^*]+\*\*)/g).filter(Boolean);return p.map((x,i)=>x.startsWith("**")&&x.endsWith("**")?<strong key={i}>{x.slice(2,-2)}</strong>:x);}
function Markdown({text}:{text:string}){const lines=text.replace(/\r/g,"").split("\n"),out:ReactNode[]=[];let i=0,k=0;const cells=(x:string)=>x.trim().replace(/^\|/,"").replace(/\|$/,"").split("|").map(y=>y.trim());while(i<lines.length){const l=lines[i].trim();if(!l){i++;continue;}if(l.startsWith("|")&&i+1<lines.length&&cells(lines[i+1]).every(x=>/^:?-{3,}:?$/.test(x))){const h=cells(l),rows:string[][]=[];i+=2;while(i<lines.length&&lines[i].trim().startsWith("|")){rows.push(cells(lines[i]));i++;}out.push(<div className={styles.chatTableWrap} key={k++}><table><thead><tr>{h.map((x,j)=><th key={j}>{inline(x)}</th>)}</tr></thead><tbody>{rows.map((r,j)=><tr key={j}>{h.map((_,z)=><td key={z}>{inline(r[z]||"")}</td>)}</tr>)}</tbody></table></div>);continue;}if(/^[-*]\s+/.test(l)){const a:string[]=[];while(i<lines.length&&/^[-*]\s+/.test(lines[i].trim())){a.push(lines[i].trim().replace(/^[-*]\s+/,""));i++;}out.push(<ul key={k++}>{a.map((x,j)=><li key={j}>{inline(x)}</li>)}</ul>);continue;}const h=l.match(/^#{1,4}\s+(.+)$/);if(h){out.push(<h3 key={k++}>{inline(h[1])}</h3>);i++;continue;}out.push(<p key={k++}>{inline(l)}</p>);i++;}return <div className={styles.chatMarkdown}>{out}</div>;}

export default function VictorinoxCopilot(){
 const[messages,setMessages]=useState<Msg[]>([{role:"assistant",content:"Hola. Soy el **MGP Pricing Copilot de Victorinox**. Puedo analizar relojes, equipo de viaje, navajas/multiherramientas y cuchillos contra sus competidores relevantes."}]),[input,setInput]=useState(""),[loading,setLoading]=useState(false),[model,setModel]=useState("AI");
 const suggestions=["¿Dónde tiene Victorinox el mayor premium?","Compara relojes vs Tissot, Seiko y Citizen","¿Cómo está Victorinox en cuchillos?","¿Qué retailer tiene el precio más bajo de Victorinox?"];
 async function ask(q:string){q=q.trim();if(!q||loading)return;const next=[...messages,{role:"user" as const,content:q}];setMessages(next);setInput("");setLoading(true);trackUsageEvent("ai_query",{module:"victorinox-market"});try{const r=await fetch("/api/victorinox-pricing-chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({messages:next.slice(-14)}),credentials:"same-origin"});const d=await r.json();if(!r.ok||!d.answer)throw new Error(d.error||"Error");setMessages(x=>[...x,{role:"assistant",content:d.answer}]);setModel(String(d.model||"AI").replace(/^gpt-/i,"GPT-"));}catch(e){setMessages(x=>[...x,{role:"assistant",content:"No pude responder en este momento. **"+(e instanceof Error?e.message:"Intenta nuevamente.")+"**"}]);}finally{setLoading(false);}}
 return <section className={styles.copilot}><div className={styles.copilotHead}><div><span>MGP AI PRICING COPILOT</span><h2>Pregunta al mercado Victorinox</h2><p>Respuestas conectadas al benchmark vigente por categoría y retailer.</p></div><strong>{model}</strong></div><div className={styles.copilotGrid}><aside><span>PREGUNTAS SUGERIDAS</span>{suggestions.map(q=><button key={q} onClick={()=>void ask(q)}>{q}<b>→</b></button>)}</aside><div className={styles.chat}><div className={styles.messages}>{messages.map((m,i)=><div key={i} className={m.role==="user"?styles.userMsg:styles.aiMsg}><span>{m.role==="user"?"TÚ":"MGP COPILOT"}</span>{m.role==="assistant"?<Markdown text={m.content}/>:<p>{m.content}</p>}</div>)}{loading&&<div className={styles.aiMsg}><span>MGP COPILOT</span><p>Analizando mercado…</p></div>}</div><form onSubmit={e=>{e.preventDefault();void ask(input)}}><textarea value={input} onChange={e=>setInput(e.target.value)} rows={2} placeholder="Ej: ¿cómo está Victorinox en relojes vs Tissot?"/><button disabled={loading||!input.trim()}>{loading?"Analizando…":"Preguntar ↗"}</button></form></div></div></section>;
}
