import { NextResponse } from "next/server";
import { inflateSync } from "node:zlib";
export const dynamic="force-dynamic"; export const revalidate=0; export const maxDuration=60;
const P=[
 {po:"1082957-770-AG24",qs:"3iMGkWFdkQftbXZ6/g7dFQ==",items:[{ctl:"gvCotizacion$ctl02$lnkAdjunto",rut:"96.756.430-3",provider:"Chilexpress"},{ctl:"gvCotizacion$ctl03$lnkAdjunto",rut:"60.503.000-9",provider:"CorreosChile"}]},
 {po:"886182-36-AG24",qs:"IB5xGbCgIWejdcOp7yy1ZQ==",items:[{ctl:"gvCotizacion$ctl02$lnkAdjunto",rut:"96.756.430-3",provider:"Chilexpress"}]},
 {po:"892208-2-AG26",qs:"3jdtl+q+CYGGxbh5+t9vPw==",items:[{ctl:"gvCotizacion$ctl02$lnkAdjunto",rut:"18.828.546-5",provider:"unknown"}]}
] as const;
function dec(v:string){return v.replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&nbsp;/g," ")}
function hidden(h:string){const p=new URLSearchParams();for(const m of h.matchAll(/<input[^>]+type=["']hidden["'][^>]*>/gi)){const t=m[0],n=t.match(/name=["']([^"']+)["']/i)?.[1];if(n)p.set(n,dec(t.match(/value=["']([^"']*)["']/i)?.[1]??""))}return p}
function cookies(h:Headers){const a=h as Headers&{getSetCookie?:()=>string[]};const raw=a.getSetCookie?.()??(h.get("set-cookie")?[h.get("set-cookie") as string]:[]);const o:string[]=[];for(const s of raw)for(const m of s.matchAll(/(?:^|,\s*)([A-Za-z0-9_.-]+=[^;,]+)/g))o.push(m[1]);return [...new Set(o)].join("; ")}
async function source(qs:string){const url=`https://www.mercadopublico.cl/PurchaseOrder/Modules/PO/DetailsPurchaseOrder.aspx?qs=${encodeURIComponent(qs)}`;const r=await fetch(url,{cache:"no-store",headers:{"user-agent":"Mozilla/5.0"}});return{url,html:await r.text(),cookie:cookies(r.headers)}}
async function file(url:string,html:string,cookie:string,ctl:string){const p=hidden(html);p.set("__EVENTTARGET",ctl);p.set("__EVENTARGUMENT","");const r=await fetch(url,{method:"POST",cache:"no-store",redirect:"follow",headers:{"user-agent":"Mozilla/5.0","content-type":"application/x-www-form-urlencoded",...(cookie?{cookie}:{})},body:p.toString()});return Buffer.from(await r.arrayBuffer())}
function unescapePdf(s:string){let out="";for(let i=0;i<s.length;i++){if(s[i]!=="\\"){out+=s[i];continue}i++;if(i>=s.length)break;const c=s[i];if(c==="n")out+="\n";else if(c==="r")out+="\r";else if(c==="t")out+="\t";else if(c==="b")out+="\b";else if(c==="f")out+="\f";else if(c==="("||c===")"||c==="\\")out+=c;else if(/[0-7]/.test(c)){let oct=c;for(let j=0;j<2&&i+1<s.length&&/[0-7]/.test(s[i+1]);j++)oct+=s[++i];out+=String.fromCharCode(parseInt(oct,8))}else if(c==="\r"&&s[i+1]==="\n")i++;else if(c!=="\n"&&c!=="\r")out+=c}return out}
function literalStrings(s:string){const out:string[]=[];for(let i=0;i<s.length;i++){if(s[i]!=="(")continue;let depth=1,raw="";for(i=i+1;i<s.length&&depth>0;i++){const c=s[i];if(c==="\\"){raw+=c;if(i+1<s.length)raw+=s[++i];continue}if(c==="("){depth++;raw+=c;continue}if(c===")"){depth--;if(depth===0)break;raw+=c;continue}raw+=c}const v=unescapePdf(raw).replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,"").trim();if(v)out.push(v)}return out}
function rawText(b:Buffer){const bin=b.toString("latin1");const chunks:string[]=[];let pos=0;while(true){const si=bin.indexOf("stream",pos);if(si<0)break;let start=si+6;if(bin[start]==="\r"&&bin[start+1]==="\n")start+=2;else if(bin[start]==="\n"||bin[start]==="\r")start++;const ei=bin.indexOf("endstream",start);if(ei<0)break;let end=ei;while(end>start&&(bin[end-1]==="\n"||bin[end-1]==="\r"))end--;const raw=b.subarray(start,end);const header=bin.slice(Math.max(0,bin.lastIndexOf("obj",si)-250),si);try{const decoded=/FlateDecode/.test(header)?inflateSync(raw):raw;const text=decoded.toString("latin1");const strings=literalStrings(text);if(strings.length)chunks.push(strings.join(" | "))}catch{}pos=ei+9}return chunks.join("\n").replace(/\s*\|\s*/g," | ").slice(0,50000)}
export async function GET(){const results:any[]=[];for(const x of P){const s=await source(x.qs);for(const i of x.items){try{const b=await file(s.url,s.html,s.cookie,i.ctl);results.push({po:x.po,rut:i.rut,provider:i.provider,bytes:b.length,text:rawText(b)})}catch(e){results.push({po:x.po,rut:i.rut,provider:i.provider,error:e instanceof Error?e.message:"error"})}}}return NextResponse.json({ok:true,results},{headers:{"cache-control":"no-store"}})}
