import LegalPage from "../LegalPage";
import styles from "../legal.module.css";

export const metadata = { title: "Información pública de mercado | MGP Super Precios", description: "Criterios sobre información pública de precios, promociones y disponibilidad." };

export default function PublicInfoPage(){return <LegalPage title="Información pública de mercado" intro="Cómo interpretamos y presentamos precios, promociones, disponibilidad, surtido y otras señales comerciales visibles públicamente en el mercado.">
  <section><h2>1. Naturaleza de la información</h2><p>MGP Super Precios consolida observaciones de mercado obtenidas desde fuentes accesibles públicamente y las transforma en estructuras comparables, tendencias, alertas y análisis. La plataforma no representa a los retailers, marcas o sitios observados, salvo que exista un acuerdo específico que indique lo contrario.</p></section>
  <section><h2>2. Precios y promociones</h2><p>Un precio observado corresponde a una captura realizada en un momento y contexto determinados. Puede variar por ubicación, sesión, disponibilidad, medio de pago, programa de fidelización, condición promocional, despacho, stock u otras reglas del comercio.</p><p>Por ello, los valores mostrados deben entenderse como inteligencia de mercado y no como una oferta contractual, cotización oficial ni garantía de precio vigente.</p></section>
  <section><h2>3. Frecuencia y actualización</h2><p>La plataforma busca actualizar las fuentes de acuerdo con su cobertura y frecuencia configurada. Sin embargo, un retailer puede cambiar su sitio, bloquear accesos, modificar estructuras, retirar productos o actualizar información entre una captura y otra. La fecha de observación y el contexto del dato deben considerarse al tomar decisiones.</p></section>
  <section><h2>4. Matching y normalización</h2><p>Para comparar productos, MGP puede normalizar nombres, marcas, formatos, packs, unidades, categorías y otras características. Los procesos automáticos y de IA pueden producir falsos positivos o comparaciones imperfectas, especialmente cuando una ficha pública tiene información incompleta.</p><p>Cuando una decisión sea crítica, recomendamos revisar el producto fuente y validar que el comparable corresponda realmente al mismo SKU o a una alternativa comercial pertinente.</p></section>
  <section><h2>5. Marcas y contenido de terceros</h2><p>Los nombres comerciales, marcas, imágenes, descripciones y otros elementos de terceros pertenecen a sus respectivos titulares. Su presencia en la plataforma busca identificar productos y fuentes para fines de análisis y no implica patrocinio, asociación o autorización comercial por parte de esos titulares.</p></section>
  <section><h2>6. Correcciones</h2><p>Si detectas un precio, clasificación, producto, marca o fuente incorrecta, puedes reportarlo para revisión. La corrección de una observación no implica necesariamente que el dato original haya sido incorrecto en el momento de captura; puede haber cambiado posteriormente.</p><div className={styles.contact}><strong>Reportar un dato</strong><a href="mailto:sebastian@mgpconsultoria.cl">sebastian@mgpconsultoria.cl</a><a href="tel:+56982315934">+56 9 8231 5934</a></div></section>
</LegalPage>}
