import LegalPage from "../LegalPage";
import styles from "../legal.module.css";

export const metadata = { title: "Privacidad y seguridad | MGP Super Precios", description: "Política de privacidad y seguridad de MGP Super Precios." };

export default function PrivacyPage(){return <LegalPage title="Privacidad y seguridad" intro="Cómo tratamos los datos personales asociados a cuentas, trials, contacto comercial y uso de MGP Super Precios, y qué controles aplicamos para proteger el acceso a la plataforma.">
  <div className={styles.notice}>Esta política describe el funcionamiento actual del servicio en Chile. La Ley N° 21.719, que modifica el régimen chileno de protección de datos personales, entra en vigencia el 1 de diciembre de 2026; MGP podrá actualizar esta política y sus procesos para reflejar ese marco normativo.</div>
  <section><h2>1. Qué datos tratamos</h2><p>Podemos tratar datos que entregas directamente al crear una cuenta, solicitar una demo, contactar soporte o usar la plataforma.</p><ul><li>Identificación y contacto: nombre, correo, teléfono y cargo.</li><li>Información de empresa: nombre de la organización, industria, plan de interés y configuración contratada.</li><li>Datos de cuenta: identificadores de usuario, organización, roles, estado de trial y preferencias.</li><li>Datos de uso y seguridad: accesos, última actividad, registros técnicos, eventos de seguridad y acciones administrativas.</li><li>Información comercial: origen de campaña, etapa de oportunidad, plan cotizado, notas de seguimiento y estado de conversión.</li></ul></section>
  <section><h2>2. Para qué usamos estos datos</h2><ul><li>Crear, autenticar y administrar cuentas y organizaciones.</li><li>Prestar la plataforma y aplicar permisos, alcance y límites contratados.</li><li>Realizar onboarding, soporte y comunicaciones operativas.</li><li>Gestionar trials, propuestas, renovación, facturación y relación comercial.</li><li>Prevenir abuso, investigar incidentes y proteger la integridad del servicio.</li><li>Mejorar funcionalidades, calidad y experiencia de uso mediante análisis agregados.</li></ul><p>No diseñamos el servicio para vender bases de datos personales de nuestros usuarios a terceros.</p></section>
  <section><h2>3. Infraestructura y proveedores</h2><p>MGP Super Precios utiliza proveedores tecnológicos para autenticación, infraestructura, alojamiento, base de datos, despliegue y funciones de inteligencia artificial. Estos proveedores pueden procesar la información necesaria para prestar esos servicios. Las credenciales y secretos de integración se mantienen fuera del navegador cuando corresponde.</p><p>Cuando usas funciones generativas, parte del contenido de la consulta y del contexto estrictamente necesario puede ser procesado por el proveedor de IA configurado para generar la respuesta. Evita ingresar datos personales sensibles, secretos comerciales o información de terceros que no estés autorizado a compartir.</p></section>
  <section><h2>4. Controles de seguridad</h2><p>La plataforma aplica controles técnicos y organizacionales orientados a reducir acceso no autorizado, pérdida o alteración de información.</p><ul><li>Acceso mediante autenticación y sesiones protegidas.</li><li>Aislamiento por organización y controles de autorización en base de datos.</li><li>Cookies de sesión HttpOnly cuando corresponde.</li><li>Secretos y claves de servicio fuera del código del navegador.</li><li>Roles y permisos para separar funciones administrativas y de clientes.</li><li>Registros de auditoría y controles de salud para funciones críticas.</li></ul><p>Ningún sistema puede garantizar seguridad absoluta. Si detectas una vulnerabilidad o acceso sospechoso, contáctanos de inmediato.</p></section>
  <section><h2>5. Conservación y eliminación</h2><p>Conservamos los datos mientras sean necesarios para prestar el servicio, administrar la relación contractual o comercial, cumplir obligaciones legales, resolver disputas y proteger la seguridad de la plataforma. Los plazos pueden variar según el tipo de registro.</p><p>Cuando corresponda, puedes solicitar eliminación o actualización de tus datos. Algunos registros pueden mantenerse por un período adicional cuando exista una obligación legal, contractual o de seguridad que lo justifique.</p></section>
  <section><h2>6. Tus derechos</h2><p>Puedes contactarnos para solicitar acceso, rectificación, actualización, eliminación o bloqueo de información personal, según corresponda bajo la normativa vigente. Desde la entrada en vigencia del nuevo régimen chileno podrán aplicar también los derechos y procedimientos que éste establezca, incluyendo supresión, oposición y portabilidad cuando corresponda.</p></section>
  <section><h2>7. Contacto de privacidad</h2><div className={styles.contact}><strong>MGP Super Precios</strong><a href="mailto:sebastian@mgpconsultoria.cl">sebastian@mgpconsultoria.cl</a><a href="tel:+56982315934">+56 9 8231 5934</a><span>Chile</span></div></section>
</LegalPage>}
