create table if not exists public.b2b_public_annex_extractions (
  id bigint generated by default as identity primary key,
  source_record_id text not null unique,
  process_id text,
  source_url text,
  attachment_name text,
  attachment_type text,
  provider_group text,
  status text not null default 'detected',
  parser text,
  text_excerpt text,
  candidate_rates jsonb not null default '[]'::jsonb,
  process_date date,
  metadata jsonb not null default '{}'::jsonb,
  ingested_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.b2b_public_annex_extractions enable row level security;

create or replace function public.b2b_upsert_annex_extractions(p_rows jsonb)
returns integer
language plpgsql
security definer
set search_path to 'public'
as $function$
declare v_count integer := 0;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  if p_rows is null or jsonb_typeof(p_rows)<>'array' then return 0; end if;
  insert into public.b2b_public_annex_extractions(
    source_record_id,process_id,source_url,attachment_name,attachment_type,provider_group,status,parser,text_excerpt,candidate_rates,process_date,metadata,updated_at
  )
  select x.source_record_id,x.process_id,x.source_url,x.attachment_name,x.attachment_type,x.provider_group,
    coalesce(nullif(x.status,''),'detected'),x.parser,left(x.text_excerpt,12000),coalesce(x.candidate_rates,'[]'::jsonb),x.process_date,coalesce(x.metadata,'{}'::jsonb),now()
  from jsonb_to_recordset(p_rows) as x(
    source_record_id text,process_id text,source_url text,attachment_name text,attachment_type text,provider_group text,status text,parser text,text_excerpt text,candidate_rates jsonb,process_date date,metadata jsonb
  )
  where nullif(x.source_record_id,'') is not null
  on conflict(source_record_id) do update set
    process_id=excluded.process_id,source_url=excluded.source_url,attachment_name=excluded.attachment_name,attachment_type=excluded.attachment_type,
    provider_group=excluded.provider_group,status=excluded.status,parser=excluded.parser,text_excerpt=excluded.text_excerpt,candidate_rates=excluded.candidate_rates,
    process_date=excluded.process_date,metadata=excluded.metadata,updated_at=now();
  get diagnostics v_count=row_count;
  return v_count;
end;
$function$;

grant execute on function public.b2b_upsert_annex_extractions(jsonb) to authenticated;

create or replace function public.b2b_annex_extraction_summary(p_days integer default 365)
returns jsonb
language sql
security definer
set search_path to 'public'
as $function$
  select case when auth.uid() is null then '{}'::jsonb else jsonb_build_object(
    'detected',count(*),'parsed',count(*) filter(where status='parsed'),'scanned',count(*) filter(where status='scanned'),
    'noPrice',count(*) filter(where status='no_price'),'errors',count(*) filter(where status='error'),
    'candidateRates',coalesce(sum(jsonb_array_length(candidate_rates)),0),'latestDate',max(process_date),'latestIngestedAt',max(ingested_at)
  ) end
  from public.b2b_public_annex_extractions
  where coalesce(process_date,ingested_at::date)>=current_date-greatest(30,least(coalesce(p_days,365),1095));
$function$;

grant execute on function public.b2b_annex_extraction_summary(integer) to authenticated;
