create table if not exists public.b2b_public_observations (
  id bigint generated by default as identity primary key,
  source_record_id text not null unique,
  source text not null default 'mercado_publico_ocds',
  source_kind text not null,
  source_url text,
  ocid text,
  process_id text,
  provider_name text not null,
  provider_group text not null,
  buyer_name text,
  buyer_region text,
  category text not null default 'courier',
  service_type text,
  classification_code text,
  classification_name text,
  description text,
  quantity numeric,
  unit text,
  unit_price_clp numeric,
  total_amount_clp numeric,
  currency text,
  price_basis text,
  process_date date,
  observed_at timestamptz,
  raw jsonb,
  ingested_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists b2b_public_observations_category_date_idx on public.b2b_public_observations(category, process_date desc);
create index if not exists b2b_public_observations_provider_idx on public.b2b_public_observations(provider_group, process_date desc);
create index if not exists b2b_public_observations_classification_idx on public.b2b_public_observations(classification_code);

alter table public.b2b_public_observations enable row level security;

drop policy if exists b2b_public_observations_authenticated_read on public.b2b_public_observations;
create policy b2b_public_observations_authenticated_read on public.b2b_public_observations for select to authenticated using (true);

-- Ingestion and dashboard RPCs are deployed in production via the matching Supabase migration.
-- They intentionally require authenticated users and expose only public procurement data.