create table if not exists public.app_usage_sessions (
  id uuid primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  started_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  ended_at timestamptz,
  active_seconds integer not null default 0 check (active_seconds >= 0),
  page_views integer not null default 0 check (page_views >= 0),
  events_count integer not null default 0 check (events_count >= 0),
  device text,
  user_agent text,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.app_usage_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.app_usage_sessions(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_name text not null,
  module text,
  path text,
  duration_ms integer not null default 0 check (duration_ms >= 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists app_usage_sessions_org_last_seen_idx on public.app_usage_sessions(organization_id, last_seen_at desc);
create index if not exists app_usage_sessions_user_last_seen_idx on public.app_usage_sessions(user_id, last_seen_at desc);
create index if not exists app_usage_events_org_created_idx on public.app_usage_events(organization_id, created_at desc);
create index if not exists app_usage_events_user_created_idx on public.app_usage_events(user_id, created_at desc);
create index if not exists app_usage_events_event_created_idx on public.app_usage_events(event_name, created_at desc);
create index if not exists app_usage_events_module_created_idx on public.app_usage_events(module, created_at desc) where module is not null;

alter table public.app_usage_sessions enable row level security;
alter table public.app_usage_events enable row level security;

revoke all on table public.app_usage_sessions from anon, authenticated;
revoke all on table public.app_usage_events from anon, authenticated;
revoke all on sequence public.app_usage_events_id_seq from anon, authenticated;

create or replace function public.enterprise_record_usage_event(
  p_organization_id uuid,
  p_session_id uuid,
  p_event_name text,
  p_module text default null,
  p_path text default null,
  p_duration_ms integer default 0,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path to 'public','private','auth','pg_temp'
as $$
declare
  v_uid uuid := auth.uid();
  v_event text := lower(trim(coalesce(p_event_name,'')));
  v_duration integer := greatest(0, least(coalesce(p_duration_ms,0), 60000));
  v_metadata jsonb := coalesce(p_metadata,'{}'::jsonb);
  v_rows integer := 0;
begin
  if v_uid is null then
    raise exception 'unauthorized' using errcode='42501';
  end if;
  if p_organization_id is null or p_session_id is null then
    raise exception 'organization and session are required' using errcode='22023';
  end if;
  if not public.is_saas_admin() and not public.enterprise_is_org_member(p_organization_id) then
    raise exception 'forbidden' using errcode='42501';
  end if;
  if v_event !~ '^[a-z0-9_.-]{1,48}$' then
    raise exception 'invalid event name' using errcode='22023';
  end if;
  if octet_length(v_metadata::text) > 4096 then
    v_metadata := '{}'::jsonb;
  end if;

  insert into public.app_usage_sessions(
    id, organization_id, user_id, started_at, last_seen_at, ended_at,
    active_seconds, page_views, events_count, device, user_agent, metadata
  )
  values (
    p_session_id, p_organization_id, v_uid, now(), now(),
    case when v_event='session_end' then now() else null end,
    case when v_event in ('heartbeat','session_end') then ceil(v_duration / 1000.0)::integer else 0 end,
    case when v_event='page_view' then 1 else 0 end,
    1,
    nullif(left(coalesce(v_metadata->>'device',''),80),''),
    nullif(left(coalesce(v_metadata->>'userAgent',''),500),''),
    v_metadata - 'label' - 'href' - 'target'
  )
  on conflict (id) do update
    set last_seen_at = now(),
        ended_at = case when v_event='session_end' then now() else null end,
        active_seconds = public.app_usage_sessions.active_seconds
          + case when v_event in ('heartbeat','session_end') then ceil(v_duration / 1000.0)::integer else 0 end,
        page_views = public.app_usage_sessions.page_views + case when v_event='page_view' then 1 else 0 end,
        events_count = public.app_usage_sessions.events_count + 1,
        device = coalesce(public.app_usage_sessions.device, nullif(left(coalesce(v_metadata->>'device',''),80),'')),
        user_agent = coalesce(public.app_usage_sessions.user_agent, nullif(left(coalesce(v_metadata->>'userAgent',''),500),'')),
        metadata = public.app_usage_sessions.metadata || (v_metadata - 'label' - 'href' - 'target')
    where public.app_usage_sessions.user_id = v_uid
      and public.app_usage_sessions.organization_id = p_organization_id;

  get diagnostics v_rows = row_count;
  if v_rows = 0 then
    raise exception 'invalid session' using errcode='42501';
  end if;

  insert into public.app_usage_events(
    session_id, organization_id, user_id, event_name, module, path, duration_ms, metadata
  )
  values (
    p_session_id,
    p_organization_id,
    v_uid,
    v_event,
    nullif(left(trim(coalesce(p_module,'')),100),''),
    nullif(left(trim(coalesce(p_path,'')),500),''),
    v_duration,
    v_metadata
  );

  update public.user_profiles
     set last_seen_at = now(), updated_at = now()
   where user_id = v_uid;

  return jsonb_build_object('ok',true,'sessionId',p_session_id);
end;
$$;

revoke all on function public.enterprise_record_usage_event(uuid,uuid,text,text,text,integer,jsonb) from public, anon;
grant execute on function public.enterprise_record_usage_event(uuid,uuid,text,text,text,integer,jsonb) to authenticated;

create or replace function public.admin_usage_dashboard(
  p_days integer default 30,
  p_organization_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'public','private','auth','pg_temp'
as $$
declare
  v_days integer := greatest(1, least(coalesce(p_days,30),365));
  v_since timestamptz;
  v_result jsonb;
begin
  if not public.is_saas_admin() then
    raise exception 'forbidden' using errcode='42501';
  end if;

  v_since := now() - make_interval(days => v_days);

  with
  s as (
    select *
    from public.app_usage_sessions
    where last_seen_at >= v_since
      and (p_organization_id is null or organization_id = p_organization_id)
  ),
  e as (
    select *
    from public.app_usage_events
    where created_at >= v_since
      and (p_organization_id is null or organization_id = p_organization_id)
  )
  select jsonb_build_object(
    'days', v_days,
    'summary', jsonb_build_object(
      'users', (select count(distinct user_id) from s),
      'organizations', (select count(distinct organization_id) from s),
      'sessions', (select count(*) from s),
      'activeMinutes', (select coalesce(round(sum(active_seconds)::numeric / 60.0,1),0) from s),
      'avgSessionMinutes', (select coalesce(round(avg(active_seconds)::numeric / 60.0,1),0) from s),
      'pageViews', (select coalesce(sum(page_views),0) from s),
      'events', (select count(*) from e),
      'chatQueries', (select count(*) from e where event_name='chat_submit'),
      'downloads', (select count(*) from e where event_name='download'),
      'activeNow', (select count(distinct user_id) from s where ended_at is null and last_seen_at >= now()-interval '5 minutes'),
      'lastActivity', (select max(last_seen_at) from s)
    ),
    'organizations', coalesce((
      select jsonb_agg(row_data order by last_seen_at desc)
      from (
        select
          max(s.last_seen_at) as last_seen_at,
          jsonb_build_object(
            'organizationId',s.organization_id,
            'organizationName',max(o.name),
            'status',max(o.status),
            'plan',max(o.plan),
            'users',count(distinct s.user_id),
            'sessions',count(*),
            'activeMinutes',round(sum(s.active_seconds)::numeric/60.0,1),
            'pageViews',sum(s.page_views),
            'lastSeenAt',max(s.last_seen_at)
          ) as row_data
        from s
        join public.organizations o on o.id=s.organization_id
        group by s.organization_id
      ) q
    ),'[]'::jsonb),
    'users', coalesce((
      select jsonb_agg(row_data order by last_seen_at desc)
      from (
        select
          max(s.last_seen_at) as last_seen_at,
          jsonb_build_object(
            'userId',s.user_id,
            'email',max(u.email),
            'displayName',max(up.display_name),
            'jobTitle',max(up.job_title),
            'organizationId',s.organization_id,
            'organizationName',max(o.name),
            'sessions',count(*),
            'activeMinutes',round(sum(s.active_seconds)::numeric/60.0,1),
            'avgSessionMinutes',round(avg(s.active_seconds)::numeric/60.0,1),
            'pageViews',sum(s.page_views),
            'events',sum(s.events_count),
            'chatQueries',(select count(*) from e where e.user_id=s.user_id and e.organization_id=s.organization_id and e.event_name='chat_submit'),
            'downloads',(select count(*) from e where e.user_id=s.user_id and e.organization_id=s.organization_id and e.event_name='download'),
            'firstSeenAt',min(s.started_at),
            'lastSeenAt',max(s.last_seen_at),
            'activeNow',bool_or(s.ended_at is null and s.last_seen_at >= now()-interval '5 minutes'),
            'topModules',coalesce((
              select jsonb_agg(jsonb_build_object('module',m.module,'events',m.n) order by m.n desc)
              from (
                select e2.module,count(*) n
                from e e2
                where e2.user_id=s.user_id
                  and e2.organization_id=s.organization_id
                  and e2.module is not null
                group by e2.module
                order by count(*) desc
                limit 4
              ) m
            ),'[]'::jsonb)
          ) as row_data
        from s
        join auth.users u on u.id=s.user_id
        left join public.user_profiles up on up.user_id=s.user_id
        join public.organizations o on o.id=s.organization_id
        group by s.user_id,s.organization_id
        order by max(s.last_seen_at) desc
        limit 500
      ) q
    ),'[]'::jsonb),
    'recentEvents', coalesce((
      select jsonb_agg(row_data order by created_at desc)
      from (
        select
          e.created_at,
          jsonb_build_object(
            'id',e.id,
            'createdAt',e.created_at,
            'eventName',e.event_name,
            'module',e.module,
            'path',e.path,
            'durationMs',e.duration_ms,
            'metadata',e.metadata,
            'userId',e.user_id,
            'email',u.email,
            'displayName',up.display_name,
            'organizationId',e.organization_id,
            'organizationName',o.name
          ) as row_data
        from e
        join auth.users u on u.id=e.user_id
        left join public.user_profiles up on up.user_id=e.user_id
        join public.organizations o on o.id=e.organization_id
        order by e.created_at desc
        limit 500
      ) q
    ),'[]'::jsonb)
  ) into v_result;

  return v_result;
end;
$$;

revoke all on function public.admin_usage_dashboard(integer,uuid) from public, anon;
grant execute on function public.admin_usage_dashboard(integer,uuid) to authenticated;
