
create table if not exists public.automotive_financing_sources (
  id uuid primary key default gen_random_uuid(),
  source_key text not null unique,
  provider text not null,
  source_type text not null check (source_type in ('auto_finance','credit_card','consumer_credit','benchmark')),
  product_name text not null default '',
  source_url text not null,
  parser_key text not null default 'generic',
  priority integer not null default 100,
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  last_scraped_at timestamptz,
  last_status text,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.automotive_financing_observations (
  id bigint generated by default as identity primary key,
  source_id uuid not null references public.automotive_financing_sources(id) on delete cascade,
  observed_at timestamptz not null default now(),
  valid_from date,
  valid_until date,
  provider text not null,
  source_type text not null check (source_type in ('auto_finance','credit_card','consumer_credit','benchmark')),
  product_name text not null default '',
  brand text,
  model text,
  vehicle_price numeric,
  financed_price numeric,
  finance_bonus numeric,
  down_payment_pct numeric,
  down_payment_amount numeric,
  term_months integer,
  installments_count integer,
  installment_amount numeric,
  balloon_amount numeric,
  monthly_rate_pct numeric,
  annual_rate_pct numeric,
  cae_pct numeric,
  loan_amount numeric,
  credit_total_cost numeric,
  vehicle_total_cost numeric,
  fees numeric,
  min_income numeric,
  confidence text not null default 'published' check (confidence in ('published','derived','conditions_only')),
  source_url text not null,
  raw_payload jsonb not null default '{}'::jsonb
);

create index if not exists automotive_financing_obs_source_time_idx
  on public.automotive_financing_observations(source_id, observed_at desc, id desc);
create index if not exists automotive_financing_obs_provider_time_idx
  on public.automotive_financing_observations(provider, source_type, observed_at desc);

alter table public.automotive_financing_sources enable row level security;
alter table public.automotive_financing_observations enable row level security;
revoke all on public.automotive_financing_sources from anon, authenticated;
revoke all on public.automotive_financing_observations from anon, authenticated;
grant all on public.automotive_financing_sources to service_role;
grant all on public.automotive_financing_observations to service_role;
grant usage, select on sequence public.automotive_financing_observations_id_seq to service_role;

insert into public.automotive_financing_sources
(source_key,provider,source_type,product_name,source_url,parser_key,priority,metadata)
values
('forum-main','Forum','auto_finance','Crédito automotriz','https://forum.cl/','forum_conditions',120,'{"coverage":"conditions"}'),
('santander-fiat','Santander Consumer','auto_finance','Compra Inteligente · Fiat','https://www.santanderconsumer.cl/promociones/fiat','santander_promo',150,'{"brand":"Fiat","model":"Pulse"}'),
('santander-jeep','Santander Consumer','auto_finance','Compra Inteligente · Jeep','https://www.santanderconsumer.cl/promociones/jeep','santander_promo',145,'{"brand":"Jeep","model":"Renegade"}'),
('tanner-auto','Tanner','auto_finance','Crédito automotriz','https://tanner.cl/automotriz/tu-auto','tanner_conditions',115,'{"coverage":"conditions"}'),
('amicar-auto','Amicar','auto_finance','Crédito automotriz','https://amicar.cl/productos','amicar_conditions',110,'{"coverage":"conditions"}'),
('gm-financial','GM Financial','auto_finance','Financiamiento Chevrolet','https://www.gmfinancial.cl/es-cl/inicio/productos/financiamiento.html','gm_conditions',110,'{"brand":"Chevrolet","coverage":"conditions"}'),
('scotia-card-auto','Scotiabank','credit_card','Tarjeta de crédito · Automotoras','https://www.scotiabankchile.cl/Personas/cuotas-sin-interes','scotia_card_auto',150,'{"category":"automotoras"}'),
('bci-card-auto','Bci','credit_card','Tarjeta de crédito · Automotriz','https://www.bci.cl/beneficios','bci_card_auto',120,'{"category":"automotriz","coverage":"conditions"}'),
('bch-card-general','Banco de Chile','credit_card','Tarjeta de crédito · 3 CSI','https://sitiospublicos.bancochile.cl/personas/beneficios/promociones/3csi','bch_card_general',115,'{"category":"general"}'),
('bancoestado-card','BancoEstado','credit_card','Tarjeta de crédito · bienvenida','https://nwm.bancoestado.cl/content/bancoestado-public/cl/es/home/campanas-bancoestado---bancoestado-personas/2026/estan-buenas-las-tarjetas-de-credito-de-bancoestado---bancoestad.html','bancoestado_card',105,'{"coverage":"conditions"}'),
('cmf-rates','CMF','benchmark','Tasas de interés vigentes','https://www.cmfchile.cl/portal/estadisticas/626/w4-propertyvalue-29487.html','cmf_rates',90,'{"coverage":"benchmark"}')
on conflict (source_key) do update set
 provider=excluded.provider, source_type=excluded.source_type, product_name=excluded.product_name,
 source_url=excluded.source_url, parser_key=excluded.parser_key, priority=excluded.priority,
 metadata=excluded.metadata, active=true, updated_at=now();

insert into public.automotive_financing_observations
(source_id,observed_at,valid_from,valid_until,provider,source_type,product_name,brand,model,
 vehicle_price,financed_price,finance_bonus,down_payment_pct,down_payment_amount,term_months,
 installments_count,installment_amount,balloon_amount,cae_pct,loan_amount,credit_total_cost,
 vehicle_total_cost,confidence,source_url,raw_payload)
select s.id, '2026-09-24 12:00:00-03'::timestamptz, date '2026-09-01', date '2026-09-30',
 'Santander Consumer','auto_finance','Compra Inteligente · Fiat Pulse','Fiat','Pulse',
 17490000,11990000,5500000,50,5995000,25,24,142990,5995000,28.62,5995000,9426760,15421760,
 'published',s.source_url,'{"basis":"promoción pública septiembre 2026","ctcBasis":"crédito"}'::jsonb
from public.automotive_financing_sources s
where s.source_key='santander-fiat'
and not exists (select 1 from public.automotive_financing_observations o where o.source_id=s.id and o.observed_at='2026-09-24 12:00:00-03'::timestamptz);

insert into public.automotive_financing_observations
(source_id,observed_at,valid_from,valid_until,provider,source_type,product_name,brand,model,
 vehicle_price,financed_price,finance_bonus,down_payment_pct,down_payment_amount,term_months,
 installments_count,installment_amount,balloon_amount,cae_pct,loan_amount,credit_total_cost,
 vehicle_total_cost,confidence,source_url,raw_payload)
select s.id, '2026-09-24 12:00:00-03'::timestamptz, date '2026-09-01', date '2026-09-30',
 'Santander Consumer','auto_finance','Compra Inteligente · Jeep Renegade','Jeep','Renegade',
 24990000,22990000,2000000,50,11495000,25,24,314990,11495000,32.88,11495000,19054760,30549760,
 'published',s.source_url,'{"basis":"promoción pública septiembre 2026","ctcBasis":"crédito"}'::jsonb
from public.automotive_financing_sources s
where s.source_key='santander-jeep'
and not exists (select 1 from public.automotive_financing_observations o where o.source_id=s.id and o.observed_at='2026-09-24 12:00:00-03'::timestamptz);

insert into public.automotive_financing_observations
(source_id,observed_at,valid_from,valid_until,provider,source_type,product_name,monthly_rate_pct,
 term_months,installments_count,cae_pct,loan_amount,credit_total_cost,confidence,source_url,raw_payload)
select s.id,'2026-09-24 12:00:00-03'::timestamptz,date '2026-09-01',date '2026-09-30',
 'Scotiabank','credit_card','Tarjeta de crédito · Automotoras',1.19,36,36,14.74,7000000,8703073,
 'published',s.source_url,'{"termRange":"12-36","category":"viajes y automotoras","cupSubjectToAvailability":true}'::jsonb
from public.automotive_financing_sources s
where s.source_key='scotia-card-auto'
and not exists (select 1 from public.automotive_financing_observations o where o.source_id=s.id and o.observed_at='2026-09-24 12:00:00-03'::timestamptz);

insert into public.automotive_financing_observations
(source_id,observed_at,valid_from,valid_until,provider,source_type,product_name,monthly_rate_pct,
 term_months,installments_count,cae_pct,loan_amount,credit_total_cost,confidence,source_url,raw_payload)
select s.id,'2026-09-24 12:00:00-03'::timestamptz,date '2026-09-01',date '2026-09-30',
 'Banco de Chile','credit_card','Tarjeta de crédito · 3 cuotas sin interés',0,3,3,1.19,200000,200396,
 'published',s.source_url,'{"category":"compras nacionales","taxesApply":true}'::jsonb
from public.automotive_financing_sources s
where s.source_key='bch-card-general'
and not exists (select 1 from public.automotive_financing_observations o where o.source_id=s.id and o.observed_at='2026-09-24 12:00:00-03'::timestamptz);

insert into public.automotive_financing_observations
(source_id,observed_at,provider,source_type,product_name,down_payment_pct,term_months,confidence,source_url,raw_payload)
select s.id,'2026-09-24 12:00:00-03'::timestamptz,s.provider,s.source_type,s.product_name,
 case s.source_key when 'forum-main' then 20 when 'tanner-auto' then 20 when 'amicar-auto' then 10 when 'gm-financial' then 0 else null end,
 case s.source_key when 'forum-main' then 72 when 'tanner-auto' then 60 when 'amicar-auto' then 60 when 'gm-financial' then 72 when 'bci-card-auto' then 24 when 'bancoestado-card' then 12 else null end,
 'conditions_only',s.source_url,
 case s.source_key
  when 'forum-main' then '{"note":"pie desde 20%; plazo publicado hasta 72 cuotas"}'::jsonb
  when 'tanner-auto' then '{"note":"crédito convencional desde 20% de pie; 12 a 60 meses"}'::jsonb
  when 'amicar-auto' then '{"note":"crédito convencional desde 10% de pie; 12 a 60 meses"}'::jsonb
  when 'gm-financial' then '{"note":"plan tradicional 0-90% pie; 6 a 72 meses"}'::jsonb
  when 'bci-card-auto' then '{"note":"beneficio público menciona hasta 24 cuotas sin interés en comercios automotrices seleccionados; condiciones específicas pueden variar"}'::jsonb
  when 'bancoestado-card' then '{"note":"3 a 12 cuotas sin interés para tarjetas nuevas dentro de ventana de bienvenida; no es una oferta universal"}'::jsonb
  else '{}'::jsonb end
from public.automotive_financing_sources s
where s.source_key in ('forum-main','tanner-auto','amicar-auto','gm-financial','bci-card-auto','bancoestado-card')
and not exists (select 1 from public.automotive_financing_observations o where o.source_id=s.id and o.observed_at='2026-09-24 12:00:00-03'::timestamptz);

create or replace function public.automotive_financing_current(
  p_organization_id uuid,
  p_source_type text default null
) returns jsonb
language plpgsql
stable
security definer
set search_path to 'public','private','pg_temp'
as $$
declare
  v_access jsonb;
  v_offers jsonb;
  v_sources jsonb;
  v_summary jsonb;
begin
  v_access := public.enterprise_access_context(p_organization_id,'automotive');
  if p_source_type is not null and p_source_type not in ('auto_finance','credit_card','consumer_credit','benchmark') then
    raise exception 'invalid financing source type';
  end if;

  with ranked as (
    select o.*,
      row_number() over (
        partition by o.source_id, coalesce(o.product_name,''), coalesce(o.brand,''), coalesce(o.model,''), coalesce(o.term_months,-1)
        order by o.observed_at desc, o.id desc
      ) rn
    from public.automotive_financing_observations o
    join public.automotive_financing_sources s on s.id=o.source_id and s.active
    where (p_source_type is null or o.source_type=p_source_type)
      and (o.valid_until is null or o.valid_until >= (now() at time zone 'America/Santiago')::date)
  ), current_rows as (
    select * from ranked where rn=1
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'id',id::text,'sourceId',source_id::text,'provider',provider,'sourceType',source_type,
    'productName',product_name,'brand',brand,'model',model,'vehiclePrice',vehicle_price,
    'financedPrice',financed_price,'financeBonus',finance_bonus,'downPaymentPct',down_payment_pct,
    'downPaymentAmount',down_payment_amount,'termMonths',term_months,'installmentsCount',installments_count,
    'installmentAmount',installment_amount,'balloonAmount',balloon_amount,'monthlyRatePct',monthly_rate_pct,
    'annualRatePct',annual_rate_pct,'caePct',cae_pct,'loanAmount',loan_amount,'creditTotalCost',credit_total_cost,
    'vehicleTotalCost',vehicle_total_cost,'fees',fees,'minIncome',min_income,'confidence',confidence,
    'sourceUrl',source_url,'observedAt',observed_at,'validFrom',valid_from,'validUntil',valid_until,
    'raw',raw_payload
  ) order by case source_type when 'auto_finance' then 1 when 'credit_card' then 2 when 'consumer_credit' then 3 else 4 end,
  provider, product_name),'[]'::jsonb),
  jsonb_build_object(
    'providers',count(distinct provider),
    'offers',count(*),
    'autoFinance',count(*) filter(where source_type='auto_finance'),
    'creditCards',count(*) filter(where source_type='credit_card'),
    'withCae',count(*) filter(where cae_pct is not null),
    'withPublishedRate',count(*) filter(where monthly_rate_pct is not null or annual_rate_pct is not null)
  )
  into v_offers,v_summary
  from current_rows;

  select coalesce(jsonb_agg(jsonb_build_object(
    'id',s.id::text,'sourceKey',s.source_key,'provider',s.provider,'sourceType',s.source_type,
    'productName',s.product_name,'sourceUrl',s.source_url,'parserKey',s.parser_key,'priority',s.priority,
    'lastScrapedAt',s.last_scraped_at,'lastStatus',s.last_status,'lastError',s.last_error,'metadata',s.metadata
  ) order by s.priority desc,s.provider),'[]'::jsonb)
  into v_sources
  from public.automotive_financing_sources s
  where s.active and (p_source_type is null or s.source_type=p_source_type);

  return jsonb_build_object(
    'source','supabase','asOf',now(),'summary',v_summary,'offers',v_offers,'sources',v_sources,
    'methodology','Datos públicos capturados por fuente. Las simulaciones del frontend normalizan monto, pie y plazo y se muestran separadas de las condiciones publicadas.'
  );
end;
$$;

revoke all on function public.automotive_financing_current(uuid,text) from public, anon;
grant execute on function public.automotive_financing_current(uuid,text) to authenticated, service_role;

do $$
begin
  if not exists (select 1 from vault.decrypted_secrets where name='automotive_financing_worker_token') then
    perform vault.create_secret(replace(gen_random_uuid()::text,'-','') || replace(gen_random_uuid()::text,'-',''),
      'automotive_financing_worker_token','Token interno crawler financiamiento automotriz');
  end if;
end $$;

create or replace function public.verify_automotive_financing_worker_token(p_token text)
returns boolean
language sql
stable
security definer
set search_path to 'public','vault','pg_temp'
as $$
  select exists(
    select 1 from vault.decrypted_secrets
    where name='automotive_financing_worker_token'
      and decrypted_secret = coalesce(p_token,'')
  );
$$;
revoke all on function public.verify_automotive_financing_worker_token(text) from public, anon, authenticated;
grant execute on function public.verify_automotive_financing_worker_token(text) to service_role;
