-- Automotive vertical: dealership-first source registry, queueing and ingestion.
-- New full rounds start only Monday/Friday; workers may drain active queues between runs.

alter table public.catalog_crawl_runs drop constraint if exists catalog_crawl_runs_vertical_check;
alter table public.catalog_crawl_runs add constraint catalog_crawl_runs_vertical_check
  check (vertical = any (array['supermarket','department_store','pharmacy','home_improvement','automotive']::text[]));

alter table public.catalog_crawl_tasks drop constraint if exists catalog_crawl_tasks_vertical_check;
alter table public.catalog_crawl_tasks add constraint catalog_crawl_tasks_vertical_check
  check (vertical = any (array['supermarket','department_store','pharmacy','home_improvement','automotive']::text[]));

alter table public.catalog_crawl_tasks drop constraint if exists catalog_crawl_tasks_kind_check;
alter table public.catalog_crawl_tasks add constraint catalog_crawl_tasks_kind_check
  check (kind = any (array[
    'vtex_categories','vtex_page','sitemap','product_page','product_batch',
    'lider_listing','lider_browse_sitemap','lider_siteindex','lider_product_sitemap','lider_product_batch','lider_product_page',
    'retail_sitemap','retail_product_batch','retail_product_page','falabella_listing_seed','falabella_listing_page',
    'ripley_sitemap','ripley_product_batch','pharmacy_sitemap','pharmacy_listing_page','pharmacy_product_batch','pharmacy_product_page',
    'easy_browse','sodimac_listing','automotive_dealer_catalog','automotive_model_page'
  ]::text[]));

alter table public.products drop constraint if exists products_retailer_type_check;
alter table public.products add constraint products_retailer_type_check
  check (retailer_type = any (array['supermarket','department_store','pharmacy','home_improvement','automotive']::text[]));

create table if not exists public.automotive_sources (
  id bigint generated by default as identity primary key,
  source_key text not null unique,
  dealer text not null,
  source_type text not null default 'dealer' check (source_type in ('dealer','brand')),
  parser_key text not null,
  base_url text not null,
  catalog_url text not null,
  enabled boolean not null default true,
  priority smallint not null default 100,
  crawl_delay_ms integer not null default 800 check (crawl_delay_ms between 0 and 15000),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.automotive_sources enable row level security;
revoke all on public.automotive_sources from anon, authenticated;
grant select, insert, update, delete on public.automotive_sources to service_role;

create index if not exists automotive_sources_enabled_priority_idx
  on public.automotive_sources(enabled, priority, dealer);
create index if not exists catalog_crawl_tasks_automotive_queue_idx
  on public.catalog_crawl_tasks(status, available_at, id)
  where vertical='automotive';
create index if not exists products_automotive_brand_model_idx
  on public.products(brand, parent_external_id, supermarket)
  where retailer_type='automotive';

insert into public.automotive_sources(source_key,dealer,parser_key,base_url,catalog_url,priority,crawl_delay_ms,metadata)
values
  ('rosselot','Rosselot','rosselot','https://www.rosselot.cl','https://www.rosselot.cl/',10,900,
   jsonb_build_object('source_policy','dealer_primary','coverage','multi_brand','notes','Version pages expose list price, brand bonus, financing bonus and technical-sheet links.')),
  ('salazar_israel','Salazar Israel','salazar_israel','https://www.salazarisrael.cl','https://www.salazarisrael.cl/marcas',20,900,
   jsonb_build_object('source_policy','dealer_primary','coverage','multi_brand','notes','Brand/model pages expose advertised prices and bonuses; used as a complementary multi-brand source.'))
on conflict(source_key) do update set
  dealer=excluded.dealer,
  parser_key=excluded.parser_key,
  base_url=excluded.base_url,
  catalog_url=excluded.catalog_url,
  enabled=true,
  priority=excluded.priority,
  crawl_delay_ms=excluded.crawl_delay_ms,
  metadata=excluded.metadata,
  updated_at=now();

create or replace function public.start_automotive_crawl_service(p_trigger_type text default 'scheduled')
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $function$
declare
  v_local_date date := (now() at time zone 'America/Santiago')::date;
  v_run_id bigint;
  v_tasks integer := 0;
begin
  perform pg_advisory_xact_lock(824632026);

  select id into v_run_id
  from public.catalog_crawl_runs
  where vertical='automotive' and status='running'
  order by started_at desc
  limit 1;
  if v_run_id is not null then
    return jsonb_build_object('started',false,'reason','automotive_run_active','runId',v_run_id);
  end if;

  if p_trigger_type='scheduled' then
    select id into v_run_id
    from public.catalog_crawl_runs
    where vertical='automotive' and run_date=v_local_date and trigger_type='scheduled'
    order by id desc limit 1;
    if v_run_id is not null then
      return jsonb_build_object('started',false,'reason','already_scheduled','runId',v_run_id);
    end if;
  end if;

  insert into public.catalog_crawl_runs(
    status,vertical,trigger_type,run_date,window_end_at,configuration
  ) values (
    'running','automotive',p_trigger_type,v_local_date,now()+interval '20 hours',
    jsonb_build_object('strategy','dealer_first','country','CL','sourcePolicy','dealer_primary_brand_fallback')
  ) returning id into v_run_id;

  insert into public.catalog_crawl_tasks(run_id,task_key,supermarket,vertical,kind,payload,status,available_at)
  select
    v_run_id,
    format('automotive-source:%s',s.source_key),
    s.dealer,
    'automotive',
    'automotive_dealer_catalog',
    jsonb_build_object(
      'source_id',s.id,
      'source_key',s.source_key,
      'parser_key',s.parser_key,
      'url',s.catalog_url,
      'stage','root',
      'crawl_delay_ms',s.crawl_delay_ms
    ),
    'queued',
    now()
  from public.automotive_sources s
  where s.enabled
  order by s.priority,s.id;

  get diagnostics v_tasks = row_count;
  update public.catalog_crawl_runs set tasks_total=v_tasks where id=v_run_id;

  if v_tasks=0 then
    update public.catalog_crawl_runs
    set status='failed',finished_at=now(),completion_reason='no_automotive_sources'
    where id=v_run_id;
  end if;

  return jsonb_build_object('started',v_tasks>0,'runId',v_run_id,'tasks',v_tasks,'runDate',v_local_date);
end;
$function$;

revoke all on function public.start_automotive_crawl_service(text) from public,anon,authenticated;
grant execute on function public.start_automotive_crawl_service(text) to service_role;

create or replace function public.start_automotive_crawls_if_due_service()
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $function$
declare
  v_local_ts timestamp := now() at time zone 'America/Santiago';
  v_isodow integer := extract(isodow from (now() at time zone 'America/Santiago'))::integer;
begin
  if v_isodow not in (1,5) then
    return jsonb_build_object('started',false,'reason','not_monday_or_friday','localTime',v_local_ts);
  end if;
  if v_local_ts::time < time '01:30' or v_local_ts::time >= time '02:30' then
    return jsonb_build_object('started',false,'reason','outside_start_window','localTime',v_local_ts);
  end if;
  return public.start_automotive_crawl_service('scheduled');
end;
$function$;

revoke all on function public.start_automotive_crawls_if_due_service() from public,anon,authenticated;
grant execute on function public.start_automotive_crawls_if_due_service() to service_role;

create or replace function public.claim_automotive_tasks_service(p_limit integer default 4)
returns setof public.catalog_crawl_tasks
language plpgsql
security definer
set search_path=public,pg_temp
as $function$
begin
  update public.catalog_crawl_tasks
  set status='queued',claimed_at=null,available_at=now()+interval '20 seconds',
      error=left(concat_ws('; ',nullif(error,''),'Requeued stale automotive task'),4000)
  where vertical='automotive' and status='running' and claimed_at < now()-interval '12 minutes';

  return query
  with picked as (
    select id
    from public.catalog_crawl_tasks
    where vertical='automotive' and status='queued' and available_at<=now()
    order by available_at,id
    for update skip locked
    limit greatest(1,least(coalesce(p_limit,4),8))
  )
  update public.catalog_crawl_tasks t
  set status='running',claimed_at=now(),attempts=t.attempts+1,error=null
  from picked
  where t.id=picked.id
  returning t.*;
end;
$function$;

revoke all on function public.claim_automotive_tasks_service(integer) from public,anon,authenticated;
grant execute on function public.claim_automotive_tasks_service(integer) to service_role;

create or replace function public.enqueue_automotive_tasks_service(p_parent_task_id bigint,p_items jsonb)
returns integer
language plpgsql
security definer
set search_path=public,pg_temp
as $function$
declare
  v_parent public.catalog_crawl_tasks%rowtype;
  v_item jsonb;
  v_count integer := 0;
  v_kind text;
  v_url text;
  v_key text;
begin
  select * into v_parent from public.catalog_crawl_tasks where id=p_parent_task_id and vertical='automotive';
  if v_parent.id is null then raise exception 'Automotive parent task not found'; end if;

  for v_item in select value from jsonb_array_elements(coalesce(p_items,'[]'::jsonb)) loop
    v_url := nullif(v_item->>'url','');
    v_kind := coalesce(nullif(v_item->>'kind',''),'automotive_model_page');
    v_key := coalesce(nullif(v_item->>'task_key',''),md5(coalesce(v_url,'')||coalesce(v_item->>'stage','')));
    if v_url is null or v_kind not in ('automotive_dealer_catalog','automotive_model_page') then continue; end if;

    insert into public.catalog_crawl_tasks(run_id,task_key,supermarket,vertical,kind,payload,status,available_at)
    values(
      v_parent.run_id,
      'automotive:'||coalesce(v_parent.payload->>'source_key',lower(regexp_replace(v_parent.supermarket,'[^a-zA-Z0-9]+','_','g')))||':'||v_key,
      v_parent.supermarket,
      'automotive',
      v_kind,
      (v_parent.payload - 'url' - 'stage') || jsonb_build_object('url',v_url,'stage',coalesce(v_item->>'stage','model')),
      'queued',
      now()
    ) on conflict(run_id,task_key) do nothing;
    if found then v_count:=v_count+1; end if;
  end loop;

  update public.catalog_crawl_runs r
  set tasks_total=(select count(*) from public.catalog_crawl_tasks t where t.run_id=r.id)
  where r.id=v_parent.run_id;
  return v_count;
end;
$function$;

revoke all on function public.enqueue_automotive_tasks_service(bigint,jsonb) from public,anon,authenticated;
grant execute on function public.enqueue_automotive_tasks_service(bigint,jsonb) to service_role;

create or replace function public.ingest_automotive_products_service(
  p_run_id bigint,
  p_task_id bigint,
  p_dealer text,
  p_products jsonb
)
returns integer
language plpgsql
security definer
set search_path=public,pg_temp
as $function$
declare
  v_item jsonb;
  v_product_id uuid;
  v_count integer := 0;
  v_external_id text;
  v_brand text;
  v_model text;
  v_version text;
  v_list numeric;
  v_final numeric;
  v_cash numeric;
  v_meta jsonb;
begin
  for v_item in select value from jsonb_array_elements(coalesce(p_products,'[]'::jsonb)) loop
    v_external_id:=nullif(v_item->>'external_id','');
    v_brand:=nullif(v_item->>'brand','');
    v_model:=nullif(v_item->>'model','');
    v_version:=coalesce(nullif(v_item->>'version',''),v_model);
    v_list:=nullif(v_item->>'list_price','')::numeric;
    v_cash:=nullif(v_item->>'cash_price','')::numeric;
    v_final:=coalesce(nullif(v_item->>'final_price','')::numeric,v_cash,v_list);
    v_meta:=coalesce(v_item->'metadata','{}'::jsonb)
      || jsonb_build_object(
        'model',v_model,
        'version',v_version,
        'dealer',p_dealer,
        'list_price',v_list,
        'cash_price',v_cash,
        'final_price',v_final,
        'source_type','dealer',
        'captured_at',now()
      );

    if v_external_id is null or v_brand is null or v_model is null then continue; end if;

    insert into public.products(
      supermarket,external_id,name,brand,category,url,image_url,retailer_type,seller,seller_id,
      parent_external_id,variant,source_metadata,industry_slug,industry_confidence,industry_source,smart_category,updated_at
    ) values (
      p_dealer,
      v_external_id,
      coalesce(nullif(v_item->>'name',''),concat_ws(' ',v_brand,v_model,v_version)),
      v_brand,
      coalesce(nullif(v_item->>'body_type',''),'Vehículo'),
      coalesce(v_item->>'url',''),
      v_item->>'image_url',
      'automotive',
      p_dealer,
      coalesce(v_item->>'source_key',lower(regexp_replace(p_dealer,'[^a-zA-Z0-9]+','_','g'))),
      lower(v_brand)||':'||lower(v_model),
      v_version,
      v_meta,
      'automotive',1,'automotive_dealer_scraper',coalesce(nullif(v_item->>'body_type',''),'Vehículo'),now()
    )
    on conflict(supermarket,external_id) do update set
      name=excluded.name,brand=excluded.brand,category=excluded.category,url=excluded.url,image_url=coalesce(excluded.image_url,products.image_url),
      retailer_type='automotive',seller=excluded.seller,seller_id=excluded.seller_id,parent_external_id=excluded.parent_external_id,
      variant=excluded.variant,source_metadata=excluded.source_metadata,industry_slug='automotive',industry_confidence=1,
      industry_source='automotive_dealer_scraper',smart_category=excluded.smart_category,updated_at=now()
    returning id into v_product_id;

    if v_final is not null and v_final>0 then
      insert into public.price_observations(product_id,regular_price,offer_price,unit,unit_price,in_stock,observed_at,crawl_run_id)
      values(v_product_id,coalesce(v_list,v_final),v_final,'vehículo',null,true,now(),p_run_id);
    end if;
    v_count:=v_count+1;
  end loop;
  return v_count;
end;
$function$;

revoke all on function public.ingest_automotive_products_service(bigint,bigint,text,jsonb) from public,anon,authenticated;
grant execute on function public.ingest_automotive_products_service(bigint,bigint,text,jsonb) to service_role;

create or replace function public.finish_automotive_task_service(
  p_task_id bigint,
  p_success boolean,
  p_products_found integer default 0,
  p_error text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $function$
declare
  v_run_id bigint;
  v_pending integer;
  v_completed integer;
  v_failed integer;
  v_products integer;
  v_status text;
begin
  update public.catalog_crawl_tasks
  set status=case when p_success then 'completed' else 'failed' end,
      finished_at=now(),claimed_at=null,products_found=greatest(coalesce(p_products_found,0),0),
      error=case when p_success then null else left(coalesce(p_error,'automotive_task_failed'),4000) end
  where id=p_task_id and vertical='automotive'
  returning run_id into v_run_id;
  if v_run_id is null then raise exception 'Automotive task not found'; end if;

  select count(*) filter(where status in('queued','running')),
         count(*) filter(where status='completed'),
         count(*) filter(where status='failed'),
         coalesce(sum(products_found),0)
  into v_pending,v_completed,v_failed,v_products
  from public.catalog_crawl_tasks where run_id=v_run_id;

  v_status:=case when v_pending>0 then 'running' when v_failed>0 then 'completed_with_errors' else 'completed' end;
  update public.catalog_crawl_runs
  set status=v_status,tasks_total=v_pending+v_completed+v_failed,tasks_completed=v_completed,tasks_failed=v_failed,
      products_found=v_products,finished_at=case when v_pending=0 then now() else null end,
      completion_reason=case when v_pending=0 then 'automotive_queue_drained' else null end
  where id=v_run_id;

  return jsonb_build_object('runId',v_run_id,'status',v_status,'pending',v_pending,'completed',v_completed,'failed',v_failed,'products',v_products);
end;
$function$;

revoke all on function public.finish_automotive_task_service(bigint,boolean,integer,text) from public,anon,authenticated;
grant execute on function public.finish_automotive_task_service(bigint,boolean,integer,text) to service_role;

do $block$
declare v_job_id bigint;
begin
  select jobid into v_job_id from cron.job where jobname='automotive-crawl-monday-friday' order by jobid desc limit 1;
  if v_job_id is not null then perform cron.unschedule(v_job_id); end if;
  perform cron.schedule(
    'automotive-crawl-monday-friday',
    '*/10 * * * 1,5',
    'select public.start_automotive_crawls_if_due_service();'
  );
end
$block$;
