import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL"),SERVICE_ROLE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),UA="MGP-CatalogBot/1.2 (+public-catalog-research; rate-limited)";
function H(extra={}){return{apikey:SERVICE_ROLE,Authorization:`Bearer ${SERVICE_ROLE}`,"content-type":"application/json",...extra}}
async function rpc(fn,body){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${fn}`,{method:"POST",headers:H(),body:JSON.stringify(body)}),t=await r.text();if(!r.ok)throw new Error(`${fn}_${r.status}_${t.slice(0,400)}`);return t?JSON.parse(t):null}
async function loadSources(){const r=await fetch(`${SUPABASE_URL}/rest/v1/home_improvement_sources?select=retailer,source_kind,base_url,crawl_delay_ms,metadata&enabled=eq.true`,{headers:H()});if(!r.ok)throw new Error(`sources_${r.status}`);const rows=await r.json();return new Map(rows.map(x=>[x.retailer,x]))}
function num(v){if(typeof v==="number"&&Number.isFinite(v))return v;if(typeof v!=="string")return null;const x=Number(v.replace(/[^0-9,.-]/g,"").replace(/\./g,"").replace(",","."));return Number.isFinite(x)?x:null}
function text(v){return typeof v==="string"&&v.trim()?v.trim():null}function absEasy(u){if(!u)return null;try{return new URL(u,"https://www.easy.cl").toString()}catch{return u}}
function rawCategory(d){const c=d?.CategoriesFullPath??d?.ProductCategories??d?.categories;if(Array.isArray(c))return c;if(c&&typeof c==="object")return c;return c??null}
function easyProduct(row,label){const d=row?.data??row??{},id=text(d.skuId)||text(d.RefId)||text(d.id)||text(row?.id),name=text(d.SkuName)||text(d.productName)||text(d.name)||text(row?.value);if(!id||!name)return null;const selling=num(d.sellingPrice)??num(d.price),list=num(d.listPrice)??num(d.originalPrice),regular=(list&&list>0)?list:selling,offer=(selling&&selling>0&&regular&&selling<regular)?selling:null;return{external_id:id,name,brand:text(d.BrandName)||text(Array.isArray(d.brands)?d.brands[0]:d.brand),category:label,url:absEasy(text(d.DetailUrl)||text(d.url)||text(row?.url)),image_url:text(d.imageUrl)||text(d.image_url)||text(d.image),seller:text(d.sellerName)||"Easy",seller_id:text(d.sellerId)||"EASY",parent_external_id:text(d.productId),variant:text(d.variant)||text(d.SkuName),regular_price:regular,offer_price:offer,in_stock:(num(d.stockLevel)??1)>0,unit:text(d.MeasurementUnit)||"un",metadata:{source:"easy_constructor",groupLabel:label,rawCategoryPath:rawCategory(d),productCategoryIds:d.ProductCategoryIds??null,rawStock:d.stockLevel??null}}}
function pv(p){const a=Array.isArray(p?.price)?p.price:[];return num(a[0]??p?.price)}
function sodimacProduct(x,label){const id=text(x?.skuId)||text(x?.offeringId)||text(x?.productId),name=text(x?.displayName);if(!id||!name)return null;const ps=Array.isArray(x?.prices)?x.prices:[],normal=ps.find(p=>p?.type==="normalPrice"),c=ps.filter(p=>p?.type!=="normalPrice").map(pv).filter(v=>typeof v==="number"&&v>0),regular=pv(normal)??(c.length?Math.max(...c):null),best=c.length?Math.min(...c):null,offer=best&&regular&&best<regular?best:null,media=Array.isArray(x?.mediaUrls)?x.mediaUrls:[];return{external_id:id,name,brand:text(x?.brand),category:label,url:text(x?.url),image_url:text(media[0]),seller:text(x?.sellerName)||"SODIMAC",seller_id:text(x?.sellerId),parent_external_id:text(x?.productId),variant:text(x?.sellerSkuId)||text(x?.offeringId),regular_price:regular,offer_price:offer,in_stock:true,unit:"un",metadata:{source:"sodimac_next_listing",sellerSkuId:x?.sellerSkuId??null,offeringId:x?.offeringId??null,productType:x?.productType??null,isSponsored:Boolean(x?.isSponsored),gscCategoryId:x?.GSCCategoryId??null}}}
async function easy(task,s){const p=task.payload||{},page=Number(p.page||1),size=Number(p.pageSize||s.metadata?.pageSize||20),key=String(p.key||""),label=String(p.label||"Hogar y construcción"),pub=String(s.metadata?.publicKey||""),u=`${s.base_url}/browse/group_id/${encodeURIComponent(key)}?key=${encodeURIComponent(pub)}&page=${page}&num_results_per_page=${size}&section=Products`;const r=await fetch(u,{headers:{"user-agent":UA,accept:"application/json,*/*","accept-language":"es-CL,es;q=0.9"},signal:AbortSignal.timeout(35000)});if(!r.ok)throw new Error(`easy_${r.status}`);const j=await r.json(),rows=Array.isArray(j?.response?.results)?j.response.results:[],products=rows.map(x=>easyProduct(x,label)).filter(Boolean),total=Math.min(Number(j?.response?.total_num_results||0),10000);return{products,totalPages:Math.max(1,Math.ceil(total/size))}}
async function sod(task){const p=task.payload||{},page=Number(p.page||1),label=String(p.label||"Hogar y construcción"),u=new URL(String(p.url||""));u.searchParams.set("page",String(page));const r=await fetch(u.toString(),{headers:{"user-agent":UA,accept:"text/html,*/*","accept-language":"es-CL,es;q=0.9"},signal:AbortSignal.timeout(40000)});if(!r.ok)throw new Error(`sodimac_${r.status}`);const html=await r.text(),m=html.match(/<script[^>]+id=["']__NEXT_DATA__["'][^>]*>([\s\S]*?)<\/script>/i);if(!m)throw new Error("sodimac_next_data_missing");const pp=JSON.parse(m[1])?.props?.pageProps??{},rows=Array.isArray(pp.results)?pp.results:[],products=rows.map(x=>sodimacProduct(x,label)).filter(Boolean),count=Number(pp?.pagination?.count||rows.length),per=Number(pp?.pagination?.perPage||48);return{products,totalPages:Math.max(1,Math.ceil(count/Math.max(1,per)))}}
async function finish(t,ok,count=0,error=null){return await rpc("finish_home_improvement_task_service",{p_task_id:t.id,p_success:ok,p_products_found:count,p_error:error})}
async function one(t,map){try{const s=map.get(t.supermarket);if(!s)throw new Error("source_missing");const got=t.kind==="easy_browse"?await easy(t,s):await sod(t);if(Number(t.payload?.page||1)===1)await rpc("enqueue_home_improvement_pages_service",{p_task_id:t.id,p_total_pages:got.totalPages});const ing=got.products.length?await rpc("ingest_home_improvement_products_service",{p_run_id:t.run_id,p_task_id:t.id,p_retailer:t.supermarket,p_products:got.products}):0,state=await finish(t,true,Number(ing||0),null);return{id:t.id,retailer:t.supermarket,page:t.payload?.page,products:Number(ing||0),totalPages:got.totalPages,state}}catch(e){const msg=e instanceof Error?e.message:String(e);try{await finish(t,false,0,msg)}catch{}return{id:t.id,retailer:t.supermarket,page:t.payload?.page,error:msg}}}
async function pool(tasks,map){const out=new Array(tasks.length);let cur=0;async function w(){while(true){const i=cur++;if(i>=tasks.length)return;out[i]=await one(tasks[i],map)}}await Promise.all(Array.from({length:Math.min(2,Math.max(1,tasks.length))},()=>w()));return out}
Deno.serve(async req=>{if(req.method!=="POST")return new Response(JSON.stringify({error:"method_not_allowed"}),{status:405,headers:{"content-type":"application/json"}});if(!SERVICE_ROLE||req.headers.get("authorization")!==`Bearer ${SERVICE_ROLE}`)return new Response(JSON.stringify({error:"unauthorized"}),{status:401,headers:{"content-type":"application/json"}});try{const map=await loadSources(),tasks=await rpc("claim_home_improvement_tasks_service",{p_limit:10});if(!tasks.length)return new Response(JSON.stringify({ok:true,claimed:0}),{headers:{"content-type":"application/json"}});const st=Date.now(),results=await pool(tasks,map),allFail=results.every(x=>x.error);return new Response(JSON.stringify({ok:!allFail,claimed:tasks.length,durationMs:Date.now()-st,results}),{status:allFail?502:200,headers:{"content-type":"application/json","cache-control":"no-store"}})}catch(e){return new Response(JSON.stringify({error:e instanceof Error?e.message:String(e)}),{status:500,headers:{"content-type":"application/json"}})}});

